### ISSUE TITLE
Missing column "consumers" in the "queues" table

### ISSUE THREAD

**Issue by KevinZhaoCn** [kestra-io/kestra#1198]
### Issue description

Hi Team,

We test a medium-sized deployment in k8s , and got below errors. 
version info : latest-full.
database: a fresh postgresql.
BTW: We have not migrated to the latest version. We are deploying a new version in new env.
```
2023-04-26 09:10:35,464 [31mWARN [0;39m [35mmain [0;39m [36mo.f.core.internal.command.DbMigrate[0;39m Schema "public" has a version (13) that is newer than the latest available migration (2) !
2023-04-26 09:10:35,970 [34mINFO [0;39m [35mexecutor [0;39m [36mio.kestra.cli.AbstractCommand[0;39m Starting Kestra with environments [k8s, cloud, cli]
2023-04-26 09:10:36,398 [34mINFO [0;39m [35mexecutor [0;39m [36mio.kestra.cli.AbstractCommand[0;39m Server Running: http://kestra-executor-58b86886f8-k2tgx:8080/, Management server on port http://kestra-executor-58b86886f8-k2tgx:8081/health
2023-04-26 09:10:37,809 [34mINFO [0;39m [35mexecutor [0;39m [36mi.k.c.c.servers.ExecutorCommand[0;39m Executor started
2023-04-26 09:10:37,829 [1;31mERROR[0;39m [35mjdbc-queue_2[0;39m [36m.c.u.ThreadUncaughtExceptionHandlers[0;39m Caught an exception in Thread[jdbc-queue_2,5,main]. Shutting down.
org.jooq.exception.DataAccessException: SQL [select "value", "offset" from queues where ((type = CAST(? AS queue_type)) and ("consumers" is null or (NOT(CAST(? AS queue_consumers) = ANY("consumers"))))) order by "offset" asc fetch next ? rows only for update skip locked]; ERROR: column "consumers" does not exist
Position: 82
at org.jooq_3.16.9.POSTGRES.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:3097)
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
at org.jooq.impl.AbstractResultQuery.fetchMany(AbstractResultQuery.java:330)
at org.jooq.impl.SelectImpl.fetchMany(SelectImpl.java:2872)
at io.kestra.runner.postgres.PostgresQueue.receiveFetch(PostgresQueue.java:76)
at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$7(JdbcQueue.java:184)
at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:550)
at org.jooq.impl.Tools$3$1.block(Tools.java:5626)
at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
at org.jooq.impl.Tools$3.get(Tools.java:5623)
at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:598)
at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:522)
at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.FallbackExecutor.lambda$supply$0(FallbackExecutor.java:45)
at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:134)
at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:93)
at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$8(JdbcQueue.java:181)
at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$9(JdbcQueue.java:213)
at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: column "consumers" does not exist
Position: 82
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4356)
at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
... 26 common frames omitted
2023-04-26 09:10:37,830 [1;31mERROR[0;39m [35mjdbc-queue_1[0;39m [36m.c.u.ThreadUncaughtExceptionHandlers[0;39m Caught an exception in Thread[jdbc-queue_1,5,main]. Shutting down.
org.jooq.exception.DataAccessException: SQL [select "value", "offset" from queues where ((type = CAST(? AS queue_type)) and ("consumers" is null or (NOT(CAST(? AS queue_consumers) = ANY("consumers"))))) order by "offset" asc fetch next ? rows only for update skip locked]; ERROR: column "consumers" does not exist
Position: 82
at org.jooq_3.16.9.POSTGRES.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:3097)
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
at org.jooq.impl.AbstractResultQuery.fetchMany(AbstractResultQuery.java:330)
at org.jooq.impl.SelectImpl.fetchMany(SelectImpl.java:2872)
at io.kestra.runner.postgres.PostgresQueue.receiveFetch(PostgresQueue.java:76)
at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$7(JdbcQueue.java:184)
at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:550)
at org.jooq.impl.Tools$3$1.block(Tools.java:5626)
at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
at org.jooq.impl.Tools$3.get(Tools.java:5623)
at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:598)
at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:522)
at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
at net.jodah.failsafe.FallbackExecutor.lambda$supply$0(FallbackExecutor.java:45)
at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:134)
at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:93)
at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$8(JdbcQueue.java:181)
at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$9(JdbcQueue.java:213)
at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: column "consumers" does not exist
Position: 82
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) 
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4356)
at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
... 26 common frames omitted
2023-04-26 09:10:37,887 [31mWARN [0;39m [35mcommand-shutdown[0;39m [36mio.kestra.cli.AbstractCommand[0;39m Receiving shutdown ! Try to graceful exit
```

**Comment by tchiotludo** [comment]
@KevinZhaoCn, here is the current status : 
- here is the missing [columns](https://github.com/kestra-io/kestra/blob/develop/jdbc-postgres/src/main/resources/migrations/postgres/V1__initial.sql#L101)
- that we dropped [here](https://github.com/kestra-io/kestra/blob/develop/jdbc-postgres/src/main/resources/migrations/postgres/V3__queue_index.sql) 
- `Schema "public" has a version (13) that is newer than the latest available migration (2) !`  seems to say that the code is on V2 of database

So I really think that you are starting without the proper docker tag, can you confirm your docker image id please ?

**Comment by KevinZhaoCn** [comment]
Hi Team,

Thank you for your support. The issue has been resolved. We are currently unable to reproduce the issue anymore. We are not sure why the problem occurred, it may have been our mistake.

Anyway, we can close the issue now.

Thanks again.
