### ISSUE TITLE
Provide a backfill example for taxi trip data: show how to format the schedule/execution date

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1733]
### Issue description

We are trying to use date from scheduled/execution date for backfills, but can't figure out the right syntax. The result should look like:

- https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet
- https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet
- and so on.

The syntax https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{schedule.date ?? execution.startDate | date("yyyy-MM")}}.parquet doesn't seem to be correct. What's the right way?

Example flow showing that it works just fine taking monthYear as input:

```yml
id: yellow_taxi_data
namespace: dev
inputs:
  - name: monthYear
    type: STRING
    defaults: 2023-01

tasks:
  - id: downloadFromInputs
    type: io.kestra.plugin.fs.http.Download
    uri: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{inputs.monthYear}}.parquet
    method: GET
    disabled: true

  - id: downloadBasedOnDate
    type: io.kestra.plugin.fs.http.Download
    uri: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{schedule.date ?? execution.startDate | date("yyyy-MM")}}.parquet  
  
  - id: shove_it_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from: "{{outputs.downloadFile.uri}}"
    key: yellow_taxi/raw/{{ schedule.date ?? execution.startDate | date("yyyy-MM") }}/yellow_taxi_{{ schedule.date ?? execution.startDate | date("yyyy-MM") }}.parquet'
    bucket: annageller
    region: eu-central-1
    accessKeyId: "{{envs.aws_access_key_id}}"
    secretKeyId: "{{envs.aws_secret_access_key}}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 1 * *"
    disabled: true
    backfill:
      start: 2023-01-01T00:00:00Z
```

**Comment by uncledata** [comment]
Also I can't seem to download the parquet file running locally on docker. More details

This is my simplified flow:
```
id: yellow_taxi_flow
namespace: dev

inputs:
  - name: monthYear
    type: STRING
    defaults: 2023-01

tasks:

  - id: download_api_data
    type: io.kestra.plugin.fs.http.Request
    uri: [https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{](https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_%7B%7B) inputs.monthYear }}.parquet
    method: GET

  - id: shove_it_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from: "{{outputs.download_api_data.uri}}"
    key: yellow_taxi/raw/{{ monthYear }}/yellow_taxi_{{ inputs.monthYear }}.parquet'
    bucket: "tomas-data-lake"
    region: eu-central-1
    accessKeyId: "{{envs.aws_access_key_id}}"
    secretKeyId: "{{envs.aws_secret_access_key}}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 1 * *"
    backfill:
      start: 2023-01-01T00:00:00Z
```
So i'm quickly running it for one default month. File is around 45MB and I get this neat little error:

```
2023-07-12T18:43:54.405Z ERROR The received length exceeds the maximum allowed content length [10485760]
2023-07-12T18:43:54.405Z TRACE io.micronaut.http.client.exceptions.ContentLengthExceededException: The received length exceeds the maximum allowed content length [10485760]
	at io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2038)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2292)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockFirst(Flux.java:2701)
		at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:499)
		at io.kestra.plugin.fs.http.Request.run(Request.java:92)
		at io.kestra.plugin.fs.http.Request.run(Request.java:23)
		at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:635)
```
Is there some setting I've not changed to allow me to do this? I'm assuming this from the error message that exchange of this file size didn't fit in the communication buffer?

**Comment by uncledata** [comment]
In regards to backfill, same flow is fine as an example to download all historical files from start date defined in the schedule object. Using the flow as I understand it should automatically start and run the backfill, but nothing happens. Is there anything I've missed on setup?

**Comment by anna-geller** [comment]
I found the issue -- the only reason it didn't work is that the last Taxi Trip data parquet file available is from April. Those backfills for May ... July won't work:

![image](https://github.com/kestra-io/kestra/assets/86264395/c4b92a68-0adf-4ba3-a27f-cd10aecec143)

Try this to reproduce the example and verify that backfills are working as expected:

```yaml
id: taxiDataBackfill
namespace: dev

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: running backfill for file https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{schedule.date ?? execution.startDate | date("yyyy-MM")}}.parquet

triggers:
  - id: sched
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 1 * *"
    backfill:
      start: 2023-01-01T00:00:00Z
```

if the issue with file size persists, please open a dedicated issue with minimal example, ideally without backfills then (only showing the buffer issue if it persists)
