### ISSUE TITLE
null pointer on EachSequential 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#179]
```
default/tst-kestra-executor-55694d6744-d42ln[kestra-executor]: java.lang.NullPointerException: null
default/tst-kestra-executor-55694d6744-d42ln[kestra-executor]: 	at org.kestra.core.runners.RunContextLogger.logEntry(RunContextLogger.java:46)
default/tst-kestra-executor-55694d6744-d42ln[kestra-executor]: 	at org.kestra.core.runners.RunContextLogger.logEntries(RunContextLogger.java:77)
default/tst-kestra-executor-55694d6744-d42ln[kestra-executor]: 	at org.kestra.core.models.executions.Execution.newAttemptsTaskRunForFailedExecution(Execution.java:424)
```
seems to have a messsage with null
```java
        if (message.length() > MAX_MESSAGE_LENGTH) {
            split = Splitter.fixedLength(MAX_MESSAGE_LENGTH).split(message);
        } else {
            split = Collections.singletonList(message);
        }
```

**Comment by tchiotludo** [comment]
fix in https://github.com/kestra-io/kestra/commit/6abf1322c79af8770e0c782d99cc91c84789882c
