### ISSUE TITLE
Support integer values in EachParallel 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1806]
### Expected Behavior

It's unexpected that this doesn't work unless integer values are wrapped into strings e.g. "1" 

```yaml
id: unexpected
namespace: dev

tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.EachParallel
    value: [1, 2, 3] # this works ["1", "2", "3"]
    tasks:
      - id: return
        type: io.kestra.core.tasks.debugs.Return
        format: "{{taskrun.value}}"
```

### Actual Behaviour

```bash
Unable to resolve state from the Flowable task: Unknown value element type: class java.lang.Integer
io.kestra.core.exceptions.IllegalVariableEvaluationException: Unknown value element type: class java.lang.Integer
	at io.kestra.core.runners.FlowableUtils.resolveEachTasks(FlowableUtils.java:281)
	at io.kestra.core.tasks.flows.EachParallel.childTasks(EachParallel.java:132)
	at io.kestra.core.tasks.flows.EachParallel.resolveState(EachParallel.java:137)
```

### Environment Information

- Kestra Version: 0.11.0

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/kestra/pull/2539
