### ISSUE TITLE
Postgres Error on fresh installation (Migrations)

### ISSUE THREAD

**Issue by kevcomparadise** [kestra-io/kestra#2824]
### Explain the bug

Hi,

I'm trying to start Kestra via Docker compose on a fresh installation. When launching the application, I immediately encounter an error:

Could you please tell me what I should do?

```kestraio-kestra-1    | CREATE INDEX IF NOT EXISTS queues_type__offset ON queues (type, "offset");
kestraio-kestra-1    | 
kestraio-kestra-1    | 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:267)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
kestraio-kestra-1    | 	... 40 more
kestraio-kestra-1    | Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "RETURN"
kestraio-kestra-1    |   Position: 136
kestraio-kestra-1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
kestraio-kestra-1    | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
kestraio-kestra-1    | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
kestraio-kestra-1    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
kestraio-kestra-1    | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
kestraio-kestra-1    | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
kestraio-kestra-1    | 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
```

### Environment Information

- Kestra Version: develop and v0.13.4
- Run docker compose

**Comment by anna-geller** [comment]
it looks like a migration issue - have you already used that database with kestra? you can check more info here https://kestra.io/docs/administrator-guide/configuration/databases#database-migrations

if it doesn't help, feel free to share more details about your setup including your Docker Compose file

**Comment by kevcomparadise** [comment]
@anna-geller  Thanks for your reply. I just downloaded the Docker Compose file from your repository using the following link: https://raw.githubusercontent.com/kestra-io/kestra/develop/docker-compose.yml

I haven't made any modifications; I simply ran 'docker-compose up'

**Comment by anna-geller** [comment]
interesting, I couldn't reproduce 

![image](https://github.com/kestra-io/kestra/assets/86264395/aba23171-15c4-4d61-9780-eacb62b24629)


also, you should get 0.13.8 atm 

![image](https://github.com/kestra-io/kestra/assets/86264395/9a89b508-d75a-4ed1-b0ba-e71349c77dd8)


can you try running docker-compose pull to pull the latest image versions and then run docker-compose up -d?

**Comment by kevcomparadise** [comment]
This did indeed solve the issue. Thank you!
I close this issue
