### ISSUE TITLE
Failed to send mail: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found

### ISSUE THREAD

**Issue by sceptri** [kestra-io/kestra#2923]
### Explain the bug

After updating to version 0.14.* (I tried with 0.14.2, 0.14.4), sending mail via plugin-notifications no longer works. Instead, the following error is thrown
```
2024-01-25 09:17:19,855 ERROR WorkerThread f.r.3.4LSPQMWAKzlngyrSk9kbSB Failed to send email [ID: '<1061282792.1.1706170639785@sceptri-nixos>'], reason: Unknown error
org.simplejavamail.mailer.internal.MailerException: Failed to send email [ID: '<1061282792.1.1706170639785@sceptri-nixos>'], reason: Unknown error
 at org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:85)
 at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:76)
 at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
 at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:364)
 at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:349)
 at io.kestra.plugin.notifications.mail.MailSend.run(MailSend.java:208)
 at io.kestra.plugin.notifications.mail.MailSend.run(MailSend.java:33)
 at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:729)
Caused by: java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found
 at jakarta.activation.FactoryFinder.find(FactoryFinder.java:95)
 at jakarta.activation.MailcapCommandMap.getImplementation(MailcapCommandMap.java:705)
 at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)
 at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)
 at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
 at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)
 at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
 at jakarta.activation.DataHandler.writeTo(DataHandler.java:290)
 at jakarta.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1670)
 at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1888)
 at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
 at org.simplejavamail.mailer.internal.util.TransportRunner.lambda$sendMessage$0(TransportRunner.java:53)
 at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:73)
 at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:51)
 at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:69)
 ... 6 common frames omitted
```

I checked and version 0.13.9 works OK

### Environment Information

- Kestra Version: 0.14.*
- Operating System and Java Version (if not using Kestra Docker image): NixOS, jdk 17 (I triend jdk 21 as well)

**Comment by anna-geller** [comment]
thx for the issue, I was able to reproduce

![image](https://github.com/kestra-io/kestra/assets/86264395/3dc19ed1-4c3b-4d62-9076-1dd7cbf07477)
