### ISSUE TITLE
Execution topology view displays GraphUtils.java errors

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3158]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/39941478-df01-43e6-80f7-18c4f04a9b2d)

![image](https://github.com/kestra-io/kestra/assets/86264395/004970e8-b29c-400a-b0b3-c90b2d9ae6cf)

```yaml
...
        at io.kestra.core.utils.GraphUtils.sequential(GraphUtils.java:152)
        at io.kestra.core.tasks.flows.Pause.tasksTree(Pause.java:95)
        at io.kestra.core.utils.GraphUtils.fillGraph(GraphUtils.java:273)
        at io.kestra.core.utils.GraphUtils.iterate(GraphUtils.java:225)
        at io.kestra.core.utils.GraphUtils.sequential(GraphUtils.java:152)
        at io.kestra.core.tasks.flows.Pause.tasksTree(Pause.java:95)
        at io.kestra.core.utils.GraphUtils.fillGraph(GraphUtils.java:273)
        at io.kestra.core.utils.GraphUtils.iterate(GraphUtils.java:225)
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Can you copy/paste the flow YAML that trigger this exception?

**Comment by anna-geller** [comment]
```yaml
id: pause_resume
namespace: dev

tasks:
  - id: pause
    type: io.kestra.core.tasks.flows.Pause

  - id: after_pause
    type: io.kestra.core.tasks.log.Log
    message: Execution has been resumed!
```
