### ISSUE TITLE
kestra:latest-develop flow fails with SECRET type input

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3176]
### Describe the issue

Running the following sample flow (regardless of specifying the input secret value):
```
id: secret_input
namespace: kestra.debug

inputs:
  - name: secret
    type: SECRET
    required: false

tasks:
  - id: debug
    type: "io.kestra.core.tasks.log.Log"
    message: "{{ inputs.secret }}"
```
Results in an error:
```
Illegal base64 character 3b
```
Stack trace:
```
java.lang.IllegalArgumentException: Illegal base64 character 3b
	at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at io.kestra.core.encryption.EncryptionService.decrypt(EncryptionService.java:46)
	at io.kestra.core.runners.RunContext.decrypt(RunContext.java:570)
	at io.kestra.core.runners.RunContext.variables(RunContext.java:309)
	at io.kestra.core.runners.RunContext.initContext(RunContext.java:159)
	at io.kestra.core.runners.RunContext.<init>(RunContext.java:97)
	at io.kestra.core.runners.RunContextFactory.of(RunContextFactory.java:26)
	at io.kestra.core.runners.ExecutorService.lambda$handleWorkerTask$12(ExecutorService.java:617)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.kestra.core.runners.ExecutorService.handleWorkerTask(ExecutorService.java:624)
	at io.kestra.core.runners.ExecutorService.process(ExecutorService.java:145)
	at io.kestra.jdbc.runner.JdbcExecutor.lambda$executionQueue$17(JdbcExecutor.java:394)
	at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lambda$lock$26(AbstractJdbcExecutionRepository.java:916)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:530)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6216)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at org.jooq.impl.Tools$3.get(Tools.java:6213)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.FallbackExecutor.lambda$supply$0(FallbackExecutor.java:45)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:134)
	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:93)
	at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
	at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lock(AbstractJdbcExecutionRepository.java:898)
	at io.kestra.jdbc.runner.JdbcExecutor.executionQueue(JdbcExecutor.java:353)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$6(JdbcQueue.java:189)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$receiveImpl$9(JdbcQueue.java:235)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$10(JdbcQueue.java:258)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Environment

- Kestra Version: **kestra/kestra:develop-full**

**Comment by anna-geller** [comment]
as discussed, I cross-checked it works now when encryption key is set

```yaml
        kestra:
          encryption:
            secret-key: eWpDMUt5QmZSZlBTUUtraGVKVUxBYkYzMndreWRwNkk=
```

```yaml
id: secret_test
namespace: dev

inputs:
  - id: secret
    type: SECRET
    required: false

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.secret }}"
```
