### ISSUE TITLE
ForEachItem regression — the task is looking for revision 0 instead for latest revision

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3273]
### Describe the issue

Error: `Unable to find flow 'prod'.'orders' with revision '0'`

full stack trace

```Java
Unable to find flow 'prod'.'orders' with revision '0'
2024-03-13 13:09:40.700java.lang.IllegalStateException: Unable to find flow 'prod'.'orders' with revision '0'
	at io.kestra.core.runners.ExecutableUtils.lambda$subflowExecution$0(ExecutableUtils.java:85)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at io.kestra.core.runners.ExecutableUtils.subflowExecution(ExecutableUtils.java:85)
	at io.kestra.core.tasks.flows.ForEachItem$ForEachItemExecutable.lambda$createSubflowExecutions$1(ForEachItem.java:412)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at io.kestra.core.tasks.flows.ForEachItem$ForEachItemExecutable.createSubflowExecutions(ForEachItem.java:426)
	at io.kestra.core.runners.ExecutorService.lambda$handleExecutableTask$13(ExecutorService.java:661)
	at java.base/java.util.ArrayList.removeIf(Unknown Source)
	at java.base/java.util.ArrayList.removeIf(Unknown Source)
	at io.kestra.core.runners.ExecutorService.handleExecutableTask(ExecutorService.java:638)
	at io.kestra.core.runners.ExecutorService.process(ExecutorService.java:154)
	at io.kestra.ee.runner.kafka.streams.ExecutorNextTransformer.transform(ExecutorNextTransformer.java:36)
	at io.kestra.ee.runner.kafka.streams.ExecutorNextTransformer.transform(ExecutorNextTransformer.java:18)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:34)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:34)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:34)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:34)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:215)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:154)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(Pro
2024-03-13 13:09:40.701cessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:810)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:810)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:741)
	at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:97)
	at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:78)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1765)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:807)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:617)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579)
```

Reproducer: the main example in ForEachItem task docs is not working😢 

```yaml
id: orders_parallel
namespace: prod

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}" # special variable that contains the items of the batch
```

subflow:
```yaml
id: orders
namespace: prod

inputs:
  - id: order
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

### Environment

- Kestra Version: 0.15.5
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
also: 

Follow up to https://github.com/kestra-io/kestra/pull/3119 to fix the UI display so that the task group displays proper icons for the child tasks and the Gantt should still work as well.

**Comment by loicmathieu** [comment]
This is not a bug of the ForEachItem per se, the message indicates that the flow cannot be found (forget the revision 0, it just means that the revision was not passed so in fact, it means the latest).

Does it arrive only once? 

With the Kakfa runner, it means that there is an execution of a flow whereas the flow information is not yet available to the Kafka executor.
