### ISSUE TITLE
Unable to trigger execution with large file in input parameters

### ISSUE THREAD

**Issue by yvrng** [kestra-io/kestra#3419]
### Describe the issue

I get the following error when I try to trigger an execution with a large file supplied as an input parameter.

```
java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Unknown Source)
	at io.micronaut.http.server.netty.MicronautHttpData.get(MicronautHttpData.java:360)
	at io.micronaut.http.server.netty.MicronautHttpData.getString(MicronautHttpData.java:411)
	at io.micronaut.http.server.netty.body.ImmediateMultiObjectBody.toMap(ImmediateMultiObjectBody.java:103)
	at io.micronaut.http.server.netty.FormRouteCompleter.asMap(FormRouteCompleter.java:245)
	at io.micronaut.http.server.netty.NettyHttpRequest.getBody(NettyHttpRequest.java:402)
	at io.micronaut.http.server.netty.NettyHttpRequest.getBody(NettyHttpRequest.java:416)
	at io.micronaut.http.HttpMessage.getBody(HttpMessage.java:94)
	at io.micronaut.http.server.netty.NettyHttpRequest.getBody(NettyHttpRequest.java:410)
	at io.kestra.webserver.controllers.ExecutionController.create(ExecutionController.java:551)
	at io.kestra.ee.webserver.controllers.ExecutionController.create(ExecutionController.java:230)
	at io.kestra.ee.webserver.controllers.$ExecutionController$Definition$Intercepted.$$access$$create(Unknown Source)
	at io.kestra.ee.webserver.controllers.$ExecutionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.kestra.ee.webserver.controllers.$ExecutionController$Definition$Intercepted.create(Unknown Source)
	at io.kestra.ee.webserver.controllers.$ExecutionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4274)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I have the same error, whether execution is triggered by the UI or by a curl.

```
curl "https://kestra/api/v1/executions/***" -H "ContentType: multipart/form-data" -F "files=@file.ion;filename=from"
```

### Environment

- Kestra Version: EE 0.15.9
- Operating System: Kubernetes (ES/Kafka/GCS)

**Comment by loicmathieu** [comment]
Hi,
Can you confirm the file is more than 2GB large?

**Comment by yvrng** [comment]
Hi, yes, the file I wanted to use was almost 4Gb.
