### ISSUE TITLE
DeduplicateItems Fails on ion input

### ISSUE THREAD

**Issue by c-arstensen** [kestra-io/kestra#3615]
### Expected Behavior
The task should be able to deduplicate an ion file containing many messages based on a key field in those messages.

### Actual Behavior
For ion inputs, the task fails with the following error:
```
java.lang.IllegalArgumentException: [no message for java.lang.ClassCastException]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4618)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4549)
	at io.kestra.core.tasks.storages.DeduplicateItems$PebbleFieldExtractor.extract(DeduplicateItems.java:199)
	at io.kestra.core.tasks.storages.DeduplicateItems$PebbleFieldExtractor.apply(DeduplicateItems.java:180)
	at io.kestra.core.tasks.storages.DeduplicateItems.run(DeduplicateItems.java:93)
	at io.kestra.core.tasks.storages.DeduplicateItems.run(DeduplicateItems.java:30)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:769)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.lang.ClassCastException]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:531)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:504)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4596)
```
	
This error does not appear if the file is serialized to JSON using `io.kestra.plugin.serdes.json.JsonWriter` prior to being passed to DeduplicateItems.

### Example Flow
```yml
# This works
  - id: json
    type: io.kestra.plugin.serdes.json.JsonWriter
    from: "{{ trigger.uri }}"

  - id: dedup
    type: io.kestra.core.tasks.storages.DeduplicateItems
    from: "{{ outputs.json.uri }}"
    expr: "{{ key }}"

#This does not
  - id: dedup
    type: io.kestra.core.tasks.storages.DeduplicateItems
    from: "{{ trigger.uri }}"
    expr: "{{ key }}"
```

### Environment

- Kestra Version: v0.16.2
- Operating System (OS/Docker/Kubernetes): Kubernetes / GKE v1.28.7-gke.1026000
- Java Version (if you don't run kestra in Docker): 17

**Comment by fhussonnois** [comment]
Hi @c-arstensen, can you please share a more complete example to reproduce the error, more specifically, how you got the ION file from `{{ trigger.uri }}`? I did some tests using a simple ion file and everything works fine. Thank you.

**Comment by c-arstensen** [comment]
In my case the trigger.uri is coming from `io.kestra.plugin.kafka.Trigger` - The flow looks like this
```
triggers:
  - id: consumetrigger
    type: io.kestra.plugin.kafka.Trigger
    groupId: kestra-nonprodmap
    properties:
      auto.offset.reset: latest
      bootstrap.servers: "{{ secret('KAFKA_HOST') }}"
      sasl.jaas.config: >-
        org.apache.kafka.common.security.scram.ScramLoginModule required 
        username="{{ secret('KAFKA_USER') }}" 
        password="{{ secret('KAFKA_PASSWORD') }}";
      sasl.mechanism: SCRAM-SHA-512
      security.protocol: SASL_PLAINTEXT
    topicPattern: ^.*event.cnc.map
    keyDeserializer: STRING
    valueDeserializer: JSON
    # Very Important! The default pollDuration of 2.0 seconds is not long enough
    pollDuration: 10.0

tasks:
 # This fails - I can get it to work by passing trigger.uri into a jsonWriter and then reading outputs.json.uri into dedup....
  - id: dedup
    type: io.kestra.core.tasks.storages.DeduplicateItems
    from: "{{ trigger.uri }}"
    expr: "{{ key }}"
```
The messages from our topics are relatively complicated JSON structures and each message is guaranteed to have a key.

**Comment by fhussonnois** [comment]
Thank you @c-arstensen for the full example. I did found an issue on with `DeduplicateItems` when ION data contains date (which is the case for data coming from kafka).
