### ISSUE TITLE
Worker logs WARN: Worker Evaluate Failed with error 'null' when a flow with realtime triggers is deleted

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#3882]
### Describe the issue

No WARN should be logged when a realtime trigger is stopped/killed.

### Environment

- Kestra Version: 0.17
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
This is due to the fact that we kill the trigger but as we didn't wait the thread is still running and interrupted.

Sometimes it even display a stacktrace:
```
2024-06-04 17:17:27,311 WARN  worker_1     flow.realtime-pubsub-delete.trigger [namespace: company.myteam] [flow: realtime-pubsub-delete] [trigger: trigger] [date: 2024-06-04T17:17:18+02:00[Europe/Paris]] Worker Evaluate Failed with error 'java.lang.InterruptedException'
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:410)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:96)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2817)
	at io.kestra.core.runners.WorkerTriggerRealtimeThread.doRun(WorkerTriggerRealtimeThread.java:41)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	... 3 common frames omitted
```

A solution would be to add a little delay in the `AbstractWorkerTriggerThread` to wait for the thread to finish so it didn't interrupt itself.

**Comment by fhussonnois** [comment]
@loicmathieu, realtime triggers are killed when they need to be stopped, and we do wait on KILL event. But, their state is switched to `KILLED` after that. For the moment, we always log a WARN when a trigger complete with a state different from SUCCESS. see: https://github.com/kestra-io/kestra/blob/23db7dec2b025116220b817df9745ea9ac1af682/core/src/main/java/io/kestra/core/runners/Worker.java#L421-L423

Maybe should we use a CANCELLED state when a realtime trigger is killed because of the flow being changed ?

**Comment by loicmathieu** [comment]
The same issue exists for standard triggers, see https://github.com/kestra-io/kestra/issues/3969
