### ISSUE TITLE
docker compose works only once

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#397]
When I start kestra with docker compose once with `docker-compose up`, it all works.

Then I stop it with `CTRL+D`, and I want to rerun it running again `docker-compose up` and it never restarts.

**Comment by tchiotludo** [comment]
can you provide me some logs? or `docker ps`?

**Comment by eregnier** [comment]
![image](https://user-images.githubusercontent.com/5399780/141951350-455a2a74-c207-45bf-8b8a-d047aa6991c5.png)
![image](https://user-images.githubusercontent.com/5399780/141951859-514946c1-dc3c-4702-908b-a567567ec59b.png)

**Comment by tchiotludo** [comment]
Ok will look space this this error happen on the kafka side.
Seems that the connection with kafka failed and must have some error on kafka side

**Comment by eregnier** [comment]
also in the same topic I have this error in my docker traces : 
```bash
kafka_1          | [2021-11-26 21:01:18,177] ERROR Error while creating ephemeral at /brokers/ids/1001, node already exists and owner '72057796598235137' does not match current session '72057815643914241' (kafka.zk.KafkaZkClient$CheckedEphemeral)
kafka_1          | [2021-11-26 21:01:18,181] ERROR [KafkaServer id=1001] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1          | org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
kafka_1          | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126)
kafka_1          | 	at kafka.zk.KafkaZkClient$CheckedEphemeral.getAfterNodeExists(KafkaZkClient.scala:1904)
kafka_1          | 	at kafka.zk.KafkaZkClient$CheckedEphemeral.create(KafkaZkClient.scala:1842)
kafka_1          | 	at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1809)
kafka_1          | 	at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:96)
kafka_1          | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:308)
kafka_1          | 	at kafka.Kafka$.main(Kafka.scala:109)
kafka_1          | 	at kafka.Kafka.main(Kafka.scala)

```

**Comment by tchiotludo** [comment]
I think it should work now. Just cleanup your local volume before retrying: 
```bash 
docker volume rm kestra_elasticsearch-data kestra_kafka-data kestra_kestra-data kestra_zookeeper-data kestra_zookeeper-log
```
