### ISSUE TITLE
Failed to obtain JDBC Connection

### ISSUE THREAD

**Issue by cpinelatreinta** [kestra-io/kestra#4076]
### Describe the issue

The service dies, I get this error
```
2024-06-19 14:42:22,038 INFO  default-nioEventLoopGroup-1-3 io.kestra.webserver.access 2024-06-19T14:42:22.005Z | GET /api/v1/executions/search?size=10&page=1&sort=state.startDate:desc&state=FAILED&state=KILLED&state=WARNING&namespace=treinta&startDate=2024-05-20T09:42:21.019-05:00&endDate=2024-06-19T09:42:21.561-05:00 HTTP/1.1 | status: 200 | ip: 172.150.49.25 | length: 8555 | duration: 33
2024-06-19 14:42:52,016 ERROR boundedElastic-2 i.k.w.controllers.ErrorController Failed to obtain JDBC Connection
io.micronaut.data.connection.jdbc.exceptions.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:59)
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:43)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.openNewConnectionInternal(AbstractConnectionOperations.java:195)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.getConnection(AbstractConnectionOperations.java:168)
        at io.micronaut.transaction.support.AbstractTransactionOperations.openNewConnectionAndTransaction(AbstractTransactionOperations.java:541)
        at io.micronaut.transaction.support.AbstractTransactionOperations.getTransaction(AbstractTransactionOperations.java:477)
        at io.micronaut.configuration.jooq.MicronautTransactionProvider.begin(MicronautTransactionProvider.java:56)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:524)
        at org.jooq.impl.Tools$3$1.block(Tools.java:6297)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
        at org.jooq.impl.Tools$3.get(Tools.java:6294)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
        at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
        at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:143)
        at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:102)
        at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
        at io.kestra.jdbc.repository.AbstractJdbcSettingRepository.findByKey(AbstractJdbcSettingRepository.java:43)
        at io.kestra.webserver.services.BasicAuthService.configuration(BasicAuthService.java:120)
        at io.kestra.webserver.filter.AuthenticationFilter.lambda$doFilter$5(AuthenticationFilter.java:53)
        at reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain.subscribeInner(FluxSwitchMapNoPrefetch.java:210)
        at reactor.core.publisher.FluxSwitchMapNoPrefetch$SwitchMapMain.onNext(FluxSwitchMapNoPrefetch.java:164)
        at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:252)
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.micronaut.configuration.jooq.MicronautTransaction.getTxStatus()" because "transaction" is null
                at io.micronaut.configuration.jooq.MicronautTransactionProvider.getTransactionStatus(MicronautTransactionProvider.java:72)
                at io.micronaut.configuration.jooq.MicronautTransactionProvider.rollback(MicronautTransactionProvider.java:67)
                at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:554)
                ... 31 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms (total=10, active=10, idle=0, waiting=26)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:57)
        ... 38 common frames omitted
2024-06-19 14:42:52,037 ERROR jdbc-queue-WorkerTaskResult_0 .c.u.ThreadUncaughtExceptionHandlers Caught an exception in Thread[#73,jdbc-queue-WorkerTaskResult_0,5,main]. Shutting down.
io.micronaut.data.connection.jdbc.exceptions.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:59)
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:43)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.openNewConnectionInternal(AbstractConnectionOperations.java:195)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.getConnection(AbstractConnectionOperations.java:168)
        at io.micronaut.transaction.support.AbstractTransactionOperations.openNewConnectionAndTransaction(AbstractTransactionOperations.java:541)
        at io.micronaut.transaction.support.AbstractTransactionOperations.getTransaction(AbstractTransactionOperations.java:477)
        at io.micronaut.configuration.jooq.MicronautTransactionProvider.begin(MicronautTransactionProvider.java:56)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:524)
        at org.jooq.impl.Tools$3$1.block(Tools.java:6297)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
        at org.jooq.impl.Tools$3.get(Tools.java:6294)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
        at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
        at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:143)
        at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:102)
        at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
        at io.kestra.jdbc.runner.JdbcQueue.lambda$receiveImpl$9(JdbcQueue.java:213)
        at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$10(JdbcQueue.java:258)
        at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.micronaut.configuration.jooq.MicronautTransaction.getTxStatus()" because "transaction" is null
                at io.micronaut.configuration.jooq.MicronautTransactionProvider.getTransactionStatus(MicronautTransactionProvider.java:72)
                at io.micronaut.configuration.jooq.MicronautTransactionProvider.rollback(MicronautTransactionProvider.java:67)
                at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:554)
                ... 23 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms (total=10, active=10, idle=0, waiting=25)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:57)
        ... 30 common frames omitted
2024-06-19 14:42:52,039 ERROR jdbc-queue-Execution_0 .c.u.ThreadUncaughtExceptionHandlers Caught an exception in Thread[#72,jdbc-queue-Execution_0,5,main]. Shutting down.
io.micronaut.data.connection.jdbc.exceptions.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:59)
        at io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.openConnection(DefaultDataSourceConnectionOperations.java:43)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.openNewConnectionInternal(AbstractConnectionOperations.java:195)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.getConnection(AbstractConnectionOperations.java:168)
        at io.micronaut.transaction.support.AbstractTransactionOperations.openNewConnectionAndTransaction(AbstractTransactionOperations.java:541)
        at io.micronaut.transaction.support.AbstractTransactionOperations.getTransaction(AbstractTransactionOperations.java:477)
        at io.micronaut.configuration.jooq.MicronautTransactionProvider.begin(MicronautTransactionProvider.java:56)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:524)
        at org.jooq.impl.Tools$3$1.block(Tools.java:6297)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
        at org.jooq.impl.Tools$3.get(Tools.java:6294)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
        at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
```

### Environment

- Kestra Version: 0.17.4
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Slack conversation that has more context https://kestra-io.slack.com/archives/C03FQKXRK3K/p1718810912372209

**Comment by anna-geller** [comment]
Closing, the problem was the size of the RDS
