### ISSUE TITLE
Internal Server Error when trying disable a webhook in the ui

### ISSUE THREAD

**Issue by ckocyigit** [kestra-io/kestra#4204]
### Describe the issue

I've noticed that trying to disable or even toggle the "Enabled" button in the UI under: "/ui/{namespace}/{flowId}/triggers" will fail with an "Internal Server Error".

To be honest I don't think there are any particular steps to reproduce this, since I just created a flow and a webhook.

Server Logs:
```
2024-07-02 07:03:07,975 ERROR io-executor-thread-30 i.k.w.controllers.ErrorController Flow of trigger null not found
io.micronaut.http.exceptions.HttpStatusException: Flow of trigger null not found
	at io.kestra.webserver.controllers.api.TriggerController.update(TriggerController.java:177)
	at io.kestra.webserver.controllers.api.$TriggerController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4232)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

UI when I click the toggle button: 
<img width="1169" alt="image" src="https://github.com/kestra-io/kestra/assets/60385015/f91b1455-ccbb-43ea-929e-7919d289dd3a">

### Environment

- Kestra Version: 0.17.8
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by smunteankestra** [comment]
not reproducing on Kestra E0.17.8 , closing please open a new issue with more details to reproduce

https://github.com/kestra-io/kestra/assets/171780240/045c0463-154b-4b4f-9d92-51a3a79c853c
