### ISSUE TITLE
DuckDB plugin does not support DuckDBArray data type

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4303]
### Describe the issue

```
java.lang.IllegalArgumentException: Data of type 'class org.duckdb.DuckDBArray' for column '[REDACTED]' is not supported
	at io.kestra.plugin.jdbc.AbstractCellConverter.convert(AbstractCellConverter.java:81)
	at io.kestra.plugin.jdbc.duckdb.DuckDbCellConverter.convertCell(DuckDbCellConverter.java:49)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.convertCell(AbstractJdbcQuery.java:189)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.mapResultSetToMap(AbstractJdbcQuery.java:182)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.fetch(AbstractJdbcQuery.java:167)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.fetchToFile(AbstractJdbcQuery.java:148)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.run(AbstractJdbcQuery.java:109)
	at io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:231)
	at io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:32)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)```

### Environment

- Kestra Version: 17.8
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Could you share a reproducer (example flow that generates that error)? It's difficult to help otherwise. thx in advance!

**Comment by aku** [comment]
@anna-geller 
```
  - id: duckdb
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: SELECT [1, 2, 3] AS Result
    fetchOne: true
```

**Comment by KunalKumar-1** [comment]
hey @anna-geller,
has this issue been resolved ?
if not i  could work on it .

**Comment by anna-geller** [comment]
sure, go ahead and thanks in advance! 👍

**Comment by KunalKumar-1** [comment]
@anna-geller ,
I'm having little difficulty identifying the exact location of the relevant files needed to make the change. 
Could you please point out to where the `io.kestra.plugin.jdbc.duckdb.Query` and `AbstractCellConverter.convert` classes are located in the codebase?

**Comment by Ben8t** [comment]
Note: unfortunetly we have an [upstream issue](https://github.com/kestra-io/plugin-jdbc/issues/165) with DuckDB Java driver [opened in DuckDB repo](https://github.com/duckdb/duckdb-java/issues/14).[ It seems that array type has been introduced in 0.10](https://duckdb.org/docs/archive/0.10/sql/data_types/array) and Kestra plugin version is stuck to 0.8 due to the later issue.

**Comment by Ben8t** [comment]
Still not working after the fix of [this](https://github.com/kestra-io/plugin-jdbc/issues/165)

**Comment by anna-geller** [comment]
this is annoying and open for too long, @mgabelle can you have a look?

![image](https://github.com/user-attachments/assets/227e5f19-9139-4902-a449-1422b654dfcd)
