### ISSUE TITLE
Request/Bug : Use charset UTF-8 in Ion mapper

### ISSUE THREAD

**Issue by cedrelek** [kestra-io/kestra#4355]
**Request/Bug** : Is it possible to change the ion mapper to UTF-8 instead of ASCII ?

**What happens**

When I have special chars in my data (é, à, etc), it is serialized into a ION clob escaped string \x...

The ION reader does not eval the \x escape sequance, so plugins fail after as it is not JSON complient. Like MongoDB.Bulk 

Here is a stack trace of mongodb.Bulk (v0.17)

```java
2024-07-17 17:43:09.711Invalid escape sequence in JSON string '\x'.
2024-07-17 17:43:09.711org.bson.json.JsonParseException: Invalid escape sequence in JSON string '\x'.
	at org.bson.json.JsonScanner.scanString(JsonScanner.java:516)
	at org.bson.json.JsonScanner.nextToken(JsonScanner.java:92)
	at org.bson.json.JsonReader.popToken(JsonReader.java:503)
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:154)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:85)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53)
	at org.bson.codecs.BsonArrayCodec.readValue(BsonArrayCodec.java:102)
	at org.bson.codecs.BsonArrayCodec.decode(BsonArrayCodec.java:67)
	at org.bson.codecs.BsonArrayCodec.decode(BsonArrayCodec.java:37)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.BsonDocument.parse(BsonDocument.java:66)
	at io.kestra.plugin.mongodb.Bulk.lambda$ndJSonReader$0(Bulk.java:59)
	at io.kestra.core.utils.Rethrow.lambda$throwConsumer$0(Rethrow.java:50)
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:97)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
	at reactor.core.publisher.Mono.block(Mono.java:1778)
	at io.kestra.plugin.mongodb.AbstractLoad.run(AbstractLoad.java:84)
	at io.kestra.plugin.mongodb.AbstractLoad.run(AbstractLoad.java:27)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
		at reactor.core.publisher.Mono.block(Mono.java:1779)
		... 4 more
```

**The fix**

https://github.com/kestra-io/kestra/blob/5f2a9a55e0ee54eb3b33f7862c7a51b091c77f04/core/src/main/java/io/kestra/core/serializers/JacksonMapper.java#L163-L166

To be changed to : 

```java
final var textWriterBuilder = IonTextWriterBuilder.standard()
            .withCatalog(catalog)
            .withCharset(StandardCharsets.UTF_8)
            .withWriteTopLevelValuesOnNewLines(true);
```

Thank you.

**Comment by loicmathieu** [comment]
Hi,
This makes sense, but we need to evaluate if it may break existing things.

**Comment by joelsidos** [comment]
Hi all, @loicmathieu @anna-geller @tchiotludo 
What about this request please ? 
We actually have a pb in production with special chars.
As a PO, I humbely don't understand why we're talking about ASCII in Kestra which is opposite to a modern internationnally orient product isn't it ?
Do you propose a workaround for that ?
Thanks
Joël SIDOS
Data Team Leader
Visiativ

**Comment by joelsidos** [comment]
@anna-geller could you give me an approximative delay ?

**Comment by anna-geller** [comment]
for each issue, you can see planned release here

![image](https://github.com/user-attachments/assets/563640d9-e7fe-45df-aab1-5a7e8bc85476)


here are planned Release dates https://kestra.io/docs/enterprise/releases

**Comment by loicmathieu** [comment]
@joelsidos, this code has been changed since you opened this issue; we no longer fix the charset to ASCII.
Do you still have the issue on Kestra 0.19.3?

**Comment by joelsidos** [comment]
thanks @loicmathieu 
we'll try
let's keep in touch

**Comment by joelsidos** [comment]
ok in 0.19.3, thanks

**Comment by joelsidos** [comment]
you can close this issue

**Comment by loicmathieu** [comment]
Thanks @joelsidos for the confirmation.
