### ISSUE TITLE
Unable to configure globally the task runner

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#4363]
### Describe the issue

Using this plugin defaults in the Kestra configration file result in a StackOverflow error:

```yaml
  plugins:
    defaults:
      - type: io.kestra.plugin
        values:
          taskRunner:
            type: io.kestra.plugin.core.runner.Process
```

Error log:
```
2024-07-19T11:13:35.868Z 2024-07-19 11:13:35,849 WARN  default-nioEventLoopGroup-1-3 reactor.core.Exceptions throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
2024-07-19T11:13:35.868Z java.lang.StackOverflowError: null
2024-07-19T11:13:35.868Z 	at java.base/jdk.internal.reflect.Reflection.verifyModuleAccess(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.lang.reflect.AccessibleObject.verifyAccess(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
2024-07-19T11:13:35.868Z 	at io.kestra.core.utils.MapUtils.cloneMap(MapUtils.java:99)
2024-07-19T11:13:35.868Z 	at io.kestra.core.utils.MapUtils.lambda$copyMap$3(MapUtils.java:83)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReduceOps$4ReducingSink.accept(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
2024-07-19T11:13:35.868Z 	at io.kestra.core.utils.MapUtils.copyMap(MapUtils.java:76)
2024-07-19T11:13:35.868Z 	at io.kestra.core.utils.MapUtils.merge(MapUtils.java:23)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.defaults(PluginDefaultService.java:215)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.recursiveDefaults(PluginDefaultService.java:171)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.lambda$recursiveDefaults$1(PluginDefaultService.java:179)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.recursiveDefaults(PluginDefaultService.java:181)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.lambda$recursiveDefaults$1(PluginDefaultService.java:179)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.recursiveDefaults(PluginDefaultService.java:181)
2024-07-19T11:13:35.868Z 	at io.kestra.core.services.PluginDefaultService.lambda$recursiveDefaults$1(PluginDefaultService.java:179)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2024-07-19T11:13:35.868Z 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
```

### Environment

- Kestra Version: 0.17
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by prateekrai1** [comment]
Can I work on this issue?

**Comment by loicmathieu** [comment]
@prateekrai1 of course you can, but this one is tricky so maybe not the best issue to start with.

**Comment by prateekrai1** [comment]
Oh okay. Thank you for the tip @loicmathieu
