### ISSUE TITLE
Error on pipeline workflow using Python script plugin

### ISSUE THREAD

**Issue by notfounnd** [kestra-io/kestra#4473]
### Describe the issue

Reproducer:

```yaml
tasks:
  - id: verify_run_python_script
    type: io.kestra.plugin.scripts.python.Script
    description: Verify run python script
    script: |
      import logging

      logging.debug('# reading dictionary file')
      print('hello world')
```

Error: 

```
java.io.IOException: Broken pipe
```

Log:
```
java.lang.RuntimeException: java.io.IOException: Broken pipe
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:210)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at com.github.dockerjava.transport.UnixSocket$WrappedWritableByteChannel.write(UnixSocket.java:95)
	at java.base/sun.nio.ch.ChannelOutputStream.writeFully(Unknown Source)
	at java.base/sun.nio.ch.ChannelOutputStream.write(Unknown Source)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:126)
	at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.flush(BHttpConnectionBase.java:308)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.flush(DefaultBHttpClientConnection.java:68)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:144)
	at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:717)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:113)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:87)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:206)
	... 4 more
```

### Environment

- Kestra Version: 0.17.15
- Operating System (OS/Docker/Kubernetes): Docker (Podman + Compose)
- Java Version (if you don't run kestra in Docker): N/A

**Comment by anna-geller** [comment]
hey, it seems like your docker image is still on 0.17.14. can you delete the old image and repull to be sure you have the latest version? I couldn't reproduce: 

![image](https://github.com/user-attachments/assets/ee4912f4-755b-45ef-8048-43674c5e848c)

```yaml
id: repro
namespace: qa
tasks:
  - id: verify_run_python_script
    type: io.kestra.plugin.scripts.python.Script
    description: Verify run python script
    script: |
      import logging

      logging.debug('# reading dictionary file')
      print('hello world')
```

if the issue persists after that, feel free to reopen the issue. thx for the report!

**Comment by notfounnd** [comment]
Hi @anna-geller .

I done this today. But to make a double check I redone all steps:

- delete all containers, images and volumes
- download a docker compose file
- execute compose to build a clean enviroment
- execute flow

The error persisted.

![image](https://github.com/user-attachments/assets/5277694e-8e17-467d-b857-7d8fdc47aa5c)

**Comment by anna-geller** [comment]
can you provide more details about your OS and how you run kestra?

it seems that your Docker client is not running - you are getting docker HTTP client exception suggesting an issue in your docker setup (rather than a kestra issue)

if you don't want to run python in docker, make sure to switch to a Process taskRunner
