### ISSUE TITLE
KV store - new line in Value returns 500

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4483]
### Describe the issue

Preconditions: user at KV Store page

Step 1: Create a variable
Step 2 : Add a new line in ints value and save it 
Step 3: try to edit it or retrieve with a flow 

Expected: Returns varibale value
Actual: Internal server error: invalid character [“\n”] at line 1 offset 6

![image](https://github.com/user-attachments/assets/4d1afd33-c4be-495d-acf5-8a720a54e1e1)

### Environment

- Kestra Version: 1.8 develop
- Operating System (Docker):
- Java Version (Docker):

**Comment by smunteankestra** [comment]
Note: Creating or editing with new line works fine 


https://github.com/user-attachments/assets/d30eafda-1245-406e-997c-6730420b4299

**Comment by fhussonnois** [comment]
Not sure it's a UI bug: 

```
invalid character ["\n"] at line 1 offset 10
com.amazon.ion.impl.IonReaderTextRawTokensX$IonReaderTextTokenException: invalid character ["\n"] at line 1 offset 10
	at com.amazon.ion.impl.IonReaderTextRawTokensX.error(IonReaderTextRawTokensX.java:2696)
	at com.amazon.ion.impl.IonReaderTextRawTokensX.read_string_char(IonReaderTextRawTokensX.java:192)
	at com.amazon.ion.impl.IonReaderTextRawTokensX.load_double_quoted_string(IonReaderTextRawTokensX.java:2041)
	at com.amazon.ion.impl.IonReaderTextRawX.token_contents_load(IonReaderTextRawX.java:1146)
	at com.amazon.ion.impl.IonReaderTextSystemX.load_scalar_value(IonReaderTextSystemX.java:224)
	at com.amazon.ion.impl.IonReaderTextSystemX.load_once(IonReaderTextSystemX.java:90)
	at com.amazon.ion.impl.IonReaderTextSystemX.load_or_cast_cached_value(IonReaderTextSystemX.java:110)
	at com.amazon.ion.impl.IonReaderTextSystemX.stringValue(IonReaderTextSystemX.java:606)
	at com.fasterxml.jackson.dataformat.ion.IonParser.getText(IonParser.java:277)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserialize(UntypedObjectDeserializerNR.java:82)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at io.kestra.core.storages.kv.KVStore.lambda$get$0(KVStore.java:59)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:90)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.kestra.core.storages.kv.KVStore.get(KVStore.java:58)
	at io.kestra.webserver.controllers.api.KVController.get(KVController.java:48)
```
