### ISSUE TITLE
Tasks executed by default worker (workers without worker key) crashes executor

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4511]
### Describe the issue

1) Deploy two different worker groups, a default worker with no worker key, and workers with a worker key. 
2) Start any flow with tasks without a worker key (should deploy to the default worker)
3) Flow is stuck on running state, but doesn't execute any tasks.
4) Executor that attempted to try to create a task run using the default worker crashes with the following log : 

```
2024-08-01 07:27:03,095 INFO  main         org.flywaydb.core.FlywayExecutor Database: jdbc:postgresql://10.100.20.40:5432/kestra (PostgreSQL 14.11)
2024-08-01 07:27:03,143 INFO  main         o.f.core.internal.command.DbValidate Successfully validated 29 migrations (execution time 00:00.030s)
2024-08-01 07:27:03,154 INFO  main         o.f.core.internal.command.DbMigrate Current version of schema "kestra": 2.9
2024-08-01 07:27:03,158 INFO  main         o.f.core.internal.command.DbMigrate Schema "kestra" is up to date. No migration necessary.
2024-08-01 07:27:03,936 INFO  executor     io.kestra.cli.AbstractCommand Starting Kestra with environments [cli]
2024-08-01 07:27:03,944 INFO  executor     i.kestra.ee.services.LicenseService License id: 33ce2859-2e57-4a0d-be90-3f49d753068d, expires on 2027-06-26 00:00:00.000
2024-08-01 07:27:04,469 INFO  executor     i.kestra.core.plugins.PluginScanner Registered 81 core plugins (scan done in 82ms)
2024-08-01 07:27:04,649 INFO  executor     i.kestra.core.plugins.PluginScanner Registered 473 plugins from 98 groups (scan done in 177ms)
2024-08-01 07:27:05,003 INFO  executor     io.kestra.cli.AbstractCommand Server Running: http://961043c8dd4d:8080/, Management server on port http://961043c8dd4d:8081/health
2024-08-01 07:27:06,513 INFO  executor     i.k.c.c.servers.ExecutorCommand Executor started
2024-08-01 07:28:00,744 ERROR jdbc-queue-Execution_0 .c.u.ThreadUncaughtExceptionHandlers Caught an exception in Thread[#51,jdbc-queue-Execution_0,5,main]. Shutting down.
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.set(Unknown Source)
	at java.base/java.util.Collections.swap(Unknown Source)
	at java.base/java.util.Collections.reverse(Unknown Source)
	at io.kestra.ee.services.WorkerGroupService.workerGroupFromNamespaceOrTenant(WorkerGroupService.java:53)
	at io.kestra.ee.services.WorkerGroupService.resolveGroupFromJob(WorkerGroupService.java:45)
	at io.kestra.jdbc.runner.JdbcExecutor.lambda$executionQueue$7(JdbcExecutor.java:393)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.kestra.jdbc.runner.JdbcExecutor.lambda$executionQueue$13(JdbcExecutor.java:393)
	at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lambda$lock$26(AbstractJdbcExecutionRepository.java:918)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:530)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6297)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at org.jooq.impl.Tools$3.get(Tools.java:6294)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
	at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
	at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lock(AbstractJdbcExecutionRepository.java:900)
	at io.kestra.jdbc.runner.JdbcExecutor.executionQueue(JdbcExecutor.java:331)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$6(JdbcQueue.java:197)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$receiveImpl$9(JdbcQueue.java:246)
	at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$10(JdbcQueue.java:269)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-08-01 07:28:00,785 WARN  command-shutdown io.kestra.cli.AbstractCommand Receiving shutdown ! Try to graceful exit
2024-08-01 07:28:00,785 INFO  command-shutdown i.kestra.core.contexts.KestraContext Kestra server - Shutdown initiated
2024-08-01 07:28:00,785 INFO  command-shutdown i.kestra.core.contexts.KestraContext Kestra server - Shutdown completed
```

### Environment

- Kestra Version: 0.18-SNAPSHOT (8/1/2024 latest build - Issue does NOT exist in current 0.17.16 build)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by johnkm516** [comment]
Issue is already created internally. Closing.
