### ISSUE TITLE
The namespace in UploadFiles is optional but the task fails if namespace is not provided

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4517]
### Describe the issue

the namespace should be optional, inferred from the flow's namespace

error:

```bash
Cannot invoke “String.equals(Object)” because “namespace” is null
2024-08-01 19:26:31.134java.lang.NullPointerException: Cannot invoke “String.equals(Object)” because “namespace” is null
 at io.kestra.core.storages.InternalStorage.namespace(InternalStorage.java:75)
 at io.kestra.plugin.core.namespace.UploadFiles.run(UploadFiles.java:158)
 at io.kestra.plugin.core.namespace.UploadFiles.run(UploadFiles.java:32)
 at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
 at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

reproducer:

```yaml
id: add_file
namespace: company.team

inputs:
  - id: python_script
    type: FILE

tasks:
  - id: py
    type: io.kestra.plugin.core.namespace.UploadFiles
    # namespace: company.team 
    filesMap:
      main.py: "{{ inputs.python_script }}"
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
@Skraye you can batch it together with https://github.com/kestra-io/kestra/issues/4516 :)
