### ISSUE TITLE
Got ReadTimeoutException when sending a message to Teams

### ISSUE THREAD

**Issue by bellec1u** [kestra-io/kestra#4571]
### Describe the issue

On my Teams, I added the connector Incoming Webhook.

When I try to do a curl from my machine that contains Kestra, I'm able to send a message via the provided webhook.

But when I try with the following configurations on Kestra
```yaml
      - id: curl
        type: io.kestra.plugin.core.http.Request
        allowFailed: true
        uri: "<my-webhook-url>"
        method: POST
        contentType: application/json
        body: |
          { 
            "title": "test title!", 
            "text": "test"
          }

      - id: notify_on_teams
        type: io.kestra.plugin.notifications.teams.TeamsIncomingWebhook
        url: "<my-webhook-url>"
        payload: |
          { 
            "title": "test title!", 
            "text": "test"
          }
```
all of them are throwing that exception:
```
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$exchangeImpl$28(DefaultHttpClient.java:1156)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:281)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:420)
	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

After a bit of research on internet, I found that the issue can come from the default pool size so I tried to update my KESTRA_CONFIGURATION env variable with the following configuration (the mentioned one contains a lot of tests from my side) but it seems that these configurations, except for the proxy, are not applied (read-timeout is aways 10s).
```yaml
        micronaut:
          server:
            netty:
              worker:
                event-loop-group: other
          netty:
            event-loops:
              default:
                num-threads: 10
              other:
                num-threads: 20
                prefer-native-transport: true
          http:
            client:
              follow-redirects: true
              event-loop-group: other
              read-timeout: 5m
            services:
              api:
                proxy-type: http
                proxy-address: <my-proxy-url>
                follow-redirects: true
```

Thanks

### Environment

- Kestra Version:  0.17.17
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
Hi, we've tested with a sample endpoint, and we couldn't reproduce:

```yaml
id: msteams
namespace: company.team
tasks:
  - id: notify_on_teams
    type: io.kestra.plugin.notifications.teams.TeamsIncomingWebhook
    url: https://reqres.in/api/ms-teams
    payload: |
      { 
        "title": "test title!", 
        "text": "test"
      }
```

it might be a network latency/congestion, firewall, ... it seems unrelated to kestra. Can you cross-check @bellec1u?

**Comment by anna-geller** [comment]
I checked with the team, and it's not an issue related to kestra. What you can do:

1. Use the `options` property on the HTTP request task to set the timeout
2. We've opened an issue to allow the same `options` property on Teams https://github.com/kestra-io/plugin-notifications/issues/150 
3. Check your Docker network setup if you run kestra in Docker
