### ISSUE TITLE
`io.kestra.plugin.kubernetes.PodCreate` fails with outputFiles using a glob pattern eg `*.txt`

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#4649]
### Describe the issue

Expanding on the example at [PodCreate](https://kestra.io/plugins/plugin-kubernetes/tasks/io.kestra.plugin.kubernetes.podcreate#examples) and incorporating a glob pattern for [outputFiles](https://kestra.io/docs/developer-guide/scripts/output-directory#generating-outputs-from-a-script-task-using-outputfiles), quote: 

> Note how the outputFiles property is used to specify the list of files to be persisted in Kestra's internal storage. The outputFiles property supports [glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)).

However, the following flow will fail on Kestra v0.18.1.

Quick note: changing outputs from
```
    outputFiles:
      - "*.txt"
```
to
```
    outputFiles:
      - "out.txt"
```
will work as expected, but given a container extracting multiple files, their names cannot be known ahead of time.

### Sample flow:
```yaml
id: podCreate
namespace: debug

tasks:
  - id: kubernetes
    type: io.kestra.plugin.kubernetes.PodCreate
    spec:
      containers:
      - name: unittest
        image: centos
        command:
          - cp
          - "{{workingDir}}/data.txt"
          - "{{workingDir}}/out.txt"
      restartPolicy: Never
    waitUntilRunning: PT3M
    inputFiles:
      data.txt: "asdfasdfas"
    outputFiles:
      - "*.txt"
```

### Logs:
```
2024-08-14T00:20:35.201Z INFO waiting to be ended!
2024-08-14T00:20:36.394Z DEBUG ended marker uploaded
2024-08-14T00:20:36.399Z WARN Failed to delete temporary file '/tmp/65ytLXfTxnZhUsKzIs6qfP/working-dir/kestra/working-dir/*'
2024-08-14T00:20:36.399Z TRACE java.nio.file.NoSuchFileException: /tmp/65ytLXfTxnZhUsKzIs6qfP/working-dir/kestra/working-dir/*
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at io.kestra.core.storages.InternalStorage.putFile(InternalStorage.java:169)
	at io.kestra.core.storages.InternalStorage.putFile(InternalStorage.java:155)
	at io.kestra.plugin.kubernetes.AbstractPod.lambda$downloadOutputFiles$3(AbstractPod.java:105)
	at io.kestra.core.utils.Rethrow.lambda$throwConsumer$0(Rethrow.java:50)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.kestra.plugin.kubernetes.AbstractPod.downloadOutputFiles(AbstractPod.java:103)
	at io.kestra.plugin.kubernetes.PodCreate.run(PodCreate.java:235)
	at io.kestra.plugin.kubernetes.PodCreate.run(PodCreate.java:39)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)

2024-08-14T00:20:36.410Z DEBUG Received close on [Type: PodWatcher]
2024-08-14T00:20:36.420Z INFO Pod 'debug-podcreate-kubernetes-qrgz1' is deleted
2024-08-14T00:20:36.425Z ERROR /tmp/65ytLXfTxnZhUsKzIs6qfP/working-dir/kestra/working-dir/* (No such file or directory)
2024-08-14T00:20:36.425Z TRACE java.io.FileNotFoundException: /tmp/65ytLXfTxnZhUsKzIs6qfP/working-dir/kestra/working-dir/* (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at io.kestra.core.storages.InternalStorage.putFile(InternalStorage.java:165)
	at io.kestra.core.storages.InternalStorage.putFile(InternalStorage.java:155)
	at io.kestra.plugin.kubernetes.AbstractPod.lambda$downloadOutputFiles$3(AbstractPod.java:105)
	at io.kestra.core.utils.Rethrow.lambda$throwConsumer$0(Rethrow.java:50)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.kestra.plugin.kubernetes.AbstractPod.downloadOutputFiles(AbstractPod.java:103)
	at io.kestra.plugin.kubernetes.PodCreate.run(PodCreate.java:235)
	at io.kestra.plugin.kubernetes.PodCreate.run(PodCreate.java:39)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

### Environment

- Kestra Version: 0.18.1
- Operating System (OS/Docker/Kubernetes): Kubernetes

**Comment by anna-geller** [comment]
@loicmathieu I wonder whether we need something similar here to https://github.com/kestra-io/plugin-aws/pull/498
