### ISSUE TITLE
Large http head request failed 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4658]
related to https://github.com/micronaut-projects/micronaut-core/issues/6927 ? 
```yaml 
      - id: getHeader
        type: io.kestra.plugin.fs.http.Request
        method: HEAD
        uri: "https://bdnb-data.s3.fr-par.scw.cloud/bnb_export_metropole_sql_dump.tar.gz"
```

**Comment by Ben8t** [comment]
I'm still able to reproduce

![Image](https://github.com/user-attachments/assets/af4fa158-455b-407b-8988-6080456239f3)

```yaml
id: myflowtesqta
namespace: company.team
tasks:


  - id: getHeader
    type: io.kestra.plugin.core.http.Request
    method: HEAD
    uri: "https://www.data.gouv.fr/fr/datasets/r/ad4bb2f6-0f40-46d2-a636-8d2604532f74"
```

@loicmathieu don't we change something on HTTP this summer that could help solve this issue ?

**Comment by loicmathieu** [comment]
No, under the hood we still use the Micronaut HTTP Client which uses the Netty HTTP Client which didn't allow HEAD request of more than 2G content-length

**Comment by tchiotludo** [comment]
close in #6551

**Comment by Ben8t** [comment]
Reopening as the reproducer at the top of this issue still produce error:
```yaml
id: request
namespace: sanitycheck.plugin.plugin-fs

tasks:
  - id: request
    type: io.kestra.plugin.core.http.Request
    method: HEAD
    uri: "https://bdnb-data.s3.fr-par.scw.cloud/bnb_export_metropole_sql_dump.tar.gz"

  - id: purge
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
```

Trace Logs:
```yaml
java.lang.NullPointerException: Cannot invoke "org.apache.hc.core5.http.HttpEntity.getContent()" because the return value of "org.apache.hc.core5.http.ClassicHttpResponse.getEntity()" is null
	at io.kestra.core.http.HttpResponse.from(HttpResponse.java:58)
	at io.kestra.core.http.client.apache.FailedResponseInterceptor.process(FailedResponseInterceptor.java:30)
	at org.apache.hc.core5.http.protocol.DefaultHttpProcessor.process(DefaultHttpProcessor.java:117)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:119)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:113)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at io.kestra.core.http.client.HttpClient.request(HttpClient.java:251)
	at io.kestra.core.http.client.HttpClient.request(HttpClient.java:191)
	at io.kestra.plugin.core.http.Request.run(Request.java:291)
	at io.kestra.plugin.core.http.Request.run(Request.java:29)
	at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78)
	at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:62)
	at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:837)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.core.runners.Worker.callJob(Worker.java:833)
	at io.kestra.core.runners.Worker.runAttempt(Worker.java:792)
	at io.kestra.core.runners.Worker.run(Worker.java:640)
	at io.kestra.core.runners.Worker.handleTask(Worker.java:332)
	at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:261)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Reproduced on Postgres OSS - RC0

**Comment by Ben8t** [comment]
```yaml
id: request
namespace: qa

tasks:
  - id: request
    type: io.kestra.plugin.core.http.Request
    method: HEAD
    uri: 'https://proof.ovh.net/files/10Gb.dat'

  - id: purge
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
```

Previous reproducer file was not present anymore. With the reproduce above the issue doesn't appear
