### ISSUE TITLE
Cannot search triggers with MySQL backend

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4866]
### Describe the issue

With MYSQL backend, Adminstriation -> Triggers, try to execute any search. An error will pop up on the screen

![image](https://github.com/user-attachments/assets/0280242f-5439-45bb-b1a2-91afa8281c72)

```
kestra-1         | 2024-09-09 13:24:54,248 ERROR io-executor-thread-8 i.k.w.controllers.ErrorController SQL [select SQL_CALC_FOUND_ROWS `value` from `triggers` where ((MATCH (fulltext) AGAINST (? IN BOOLEAN MODE)) and `tenant_id` = ? and true) order by `trigger_id` asc limit ? offset ?]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fulltext) AGAINST ('+test1*' IN BOOLEAN MODE)) and `tenant_id` = 'default' and t' at line 1
kestra-1         | org.jooq.exception.DataAccessException: SQL [select SQL_CALC_FOUND_ROWS `value` from `triggers` where ((MATCH (fulltext) AGAINST (? IN BOOLEAN MODE)) and `tenant_id` = ? and true) order by `trigger_id` asc limit ? offset ?]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fulltext) AGAINST ('+test1*' IN BOOLEAN MODE)) and `tenant_id` = 'default' and t' at line 1
kestra-1         | 	at org.jooq_3.19.10.MYSQL_8_0_19.debug(Unknown Source)
kestra-1         | 	at org.jooq.impl.Tools.translate(Tools.java:3607)
kestra-1         | 	at org.jooq.impl.Tools.translate(Tools.java:3595)
kestra-1         | 	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
kestra-1         | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
kestra-1         | 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
kestra-1         | 	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3232)
kestra-1         | 	at io.kestra.repository.mysql.MysqlRepository.fetchPage(MysqlRepository.java:60)
kestra-1         | 	at io.kestra.jdbc.AbstractJdbcRepository.fetchPage(AbstractJdbcRepository.java:187)
kestra-1         | 	at io.kestra.jdbc.repository.AbstractJdbcTriggerRepository.lambda$find$9(AbstractJdbcTriggerRepository.java:261)
kestra-1         | 	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:530)
kestra-1         | 	at org.jooq.impl.Tools$3$1.block(Tools.java:6325)
kestra-1         | 	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
kestra-1         | 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
kestra-1         | 	at org.jooq.impl.Tools$3.get(Tools.java:6322)
kestra-1         | 	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
kestra-1         | 	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:502)
kestra-1         | 	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
kestra-1         | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
kestra-1         | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
kestra-1         | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
kestra-1         | 	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
kestra-1         | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
kestra-1         | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
kestra-1         | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
kestra-1         | 	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
kestra-1         | 	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
kestra-1         | 	at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
kestra-1         | 	at io.kestra.jdbc.repository.AbstractJdbcTriggerRepository.find(AbstractJdbcTriggerRepository.java:238)
kestra-1         | 	at io.kestra.webserver.controllers.api.TriggerController.search(TriggerController.java:76)
kestra-1         | 	at io.kestra.ee.webserver.controllers.api.TriggerController.search(TriggerController.java:46)
kestra-1         | 	at io.kestra.ee.webserver.controllers.api.$TriggerController$Definition$Exec.dispatch(Unknown Source)
kestra-1         | 	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
kestra-1         | 	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4326)
kestra-1         | 	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
kestra-1         | 	at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)
kestra-1         | 	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)
kestra-1         | 	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)
kestra-1         | 	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
kestra-1         | 	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
kestra-1         | 	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
kestra-1         | 	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
kestra-1         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
kestra-1         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
kestra-1         | 	at java.base/java.lang.Thread.run(Unknown Source)
kestra-1         | Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fulltext) AGAINST ('+test1*' IN BOOLEAN MODE)) and `tenant_id` = 'default' and t' at line 1
kestra-1         | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
kestra-1         | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
kestra-1         | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
kestra-1         | 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:359)
kestra-1         | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
kestra-1         | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
kestra-1         | 	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
kestra-1         | 	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4968)
kestra-1         | 	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
kestra-1         | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
kestra-1         | 	... 40 common frames omitted
```

### Environment

- Kestra Version: 0.18.5
- Operating System Docker w/ MySQL backend

**Comment by Harshmhajn** [comment]
can i work on this?
