### ISSUE TITLE
io.pebbletemplates.pebble.error.PebbleException: Could not perform subtraction

### ISSUE THREAD

**Issue by MarcoGriep88** [kestra-io/kestra#4947]
### Describe the issue

Hi,

at first: If its not an bug, sorry for that. I'm new to kestra.

I'm working on an flow to pull the latest e-mails that has a specific subject. I'm doing this with an python script.

I'm returning the data to kestra by this:
`
mail.close()
mail.logout()

outputs = {
    'found_mails': found,
    'count': count
}

Kestra.outputs(outputs)
`

The code runs without issues. In the Output section i'm seeing those variables with the expected values. The Output Dialog shows me following pepple Syntax to access to variables:
{{ outputs.smtp-pull-mails["vars"]["count"] }}

When i click on "Debug Outputs" i'm getting following Exception:

`
io.kestra.core.exceptions.IllegalVariableEvaluationException: io.pebbletemplates.pebble.error.PebbleException: Could not perform subtraction ({{ outputs.smtp-pull-mails["vars"]["count"] }}:1)
	at io.kestra.core.runners.VariableRenderer.properPebbleException(VariableRenderer.java:64)
	at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:120)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:91)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:76)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:68)
	at io.kestra.core.runners.DefaultRunContext.render(DefaultRunContext.java:165)
	at io.kestra.webserver.controllers.api.ExecutionController.runContextRender(ExecutionController.java:259)
	at io.kestra.webserver.controllers.api.ExecutionController.eval(ExecutionController.java:248)
	at io.kestra.webserver.controllers.api.$ExecutionController$Definition$Intercepted.$$access$$eval(Unknown Source)
	at io.kestra.webserver.controllers.api.$ExecutionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnExecutableValidator(ValidatingInterceptor.java:166)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:109)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
	at io.kestra.webserver.controllers.api.$ExecutionController$Definition$Intercepted.eval(Unknown Source)
	at io.kestra.webserver.controllers.api.$ExecutionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4326)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
	at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.pebbletemplates.pebble.error.PebbleException: Could not perform subtraction ({{ outputs.smtp-pull-mails["vars"]["count"] }}:1)
	at io.pebbletemplates.pebble.node.expression.SubtractExpression.evaluate(SubtractExpression.java:25)
	at io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
	at io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
	at io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
	at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
	at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:96)
	at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:114)
	... 28 more
Caused by: io.pebbletemplates.pebble.error.PebbleException: Could not perform subtraction ({{ outputs.smtp-pull-mails["vars"]["count"] }}:1)
	at io.pebbletemplates.pebble.node.expression.SubtractExpression.evaluate(SubtractExpression.java:25)
	at io.pebbletemplates.pebble.node.expression.SubtractExpression.evaluate(SubtractExpression.java:21)
	... 34 more
Caused by: io.pebbletemplates.pebble.error.AttributeNotFoundException: Attribute [smtp] of [java.util.HashMap] does not exist or can not be accessed and strict variables is set to true. ({{ outputs.smtp-pull-mails["vars"]["count"] }}:1)
	at io.pebbletemplates.pebble.attributes.MapResolver.resolve(MapResolver.java:45)
	at io.pebbletemplates.pebble.attributes.DefaultAttributeResolver.resolve(DefaultAttributeResolver.java:39)
	at io.pebbletemplates.pebble.node.expression.GetAttributeExpression.evaluate(GetAttributeExpression.java:83)
	at io.pebbletemplates.pebble.node.expression.SubtractExpression.evaluate(SubtractExpression.java:21)
	... 35 more
`

I get the Same Exception in further Flow-Steps like "Log Output" or "If".

`
id: geheitsdokumente-to-paperless
namespace: private
tasks:
  - id: smtp-pull-mails
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    beforeCommands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install requests kestra
    commands:
      - python smtp-pull.py
  - id: python_log
    type: io.kestra.plugin.core.log.Log
    message: '{{ outputs.smtp-pull-mails["vars"]["count"] }} Mails gefunden.'
`

> Ignore the wrong naming "smtp-pull". Its imap of cause

python_log throws same error here.

Am i wrong or is this maybe an bug?

### Environment

- Kestra Version: Latest - 0.18.6
- Operating System (OS/Docker/Kubernetes): Ubuntu Server 24.04 with Docker Version of Kestra

**Comment by MarcoGriep88** [comment]
Ok forget it. I was stupid... i should use underscore instead if -
