### ISSUE TITLE
Flakky test on scheduler 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4971]
```
  io.kestra.core.schedulers.SchedulerScheduleOnDatesTest ✘ recoverNONEMissing()

    java.lang.AssertionError: 
    Expected: is <2024-09-18T21:52:13>
         but: was <2024-09-18T21:52:14>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.kestra.core.schedulers.SchedulerScheduleOnDatesTest.recoverNONEMissing(SchedulerScheduleOnDatesTest.java:254)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
        at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:162)
        at io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:119)
        at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by tchiotludo** [comment]
```
  io.kestra.core.schedulers.SchedulerScheduleOnDatesTest ✘ recoverLASTMissing() (1.2s)

    java.lang.AssertionError: 
    Expected: is <2024-09-20T06:32:31>
         but: was <2024-09-20T06:32:33>
```
