### ISSUE TITLE
[UI] Set-labels on an execution didn't work, no forms

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5179]
### Describe the issue

[UI] Set-labels on an execution didn't work, no forms

![image](https://github.com/user-attachments/assets/5ca90327-2c8b-4910-80ac-762686fcd9f3)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
This is the error from the console:

```
TypeError: Cannot read properties of undefined (reading 'execution')
    at index-5tKd4Cpp.js:4644:8063
    at a (index-5tKd4Cpp.js:14:4056)
    at Ze (index-5tKd4Cpp.js:15:8952)
    at Proxy.<anonymous> (index-5tKd4Cpp.js:121:17639)
    at TK (index-5tKd4Cpp.js:15:34921)
    at eD.Ge [as fn] (index-5tKd4Cpp.js:15:25958)
    at eD.run (index-5tKd4Cpp.js:10:1749)
    at U (index-5tKd4Cpp.js:15:26384)
    at J (index-5tKd4Cpp.js:15:24848)
    at Z (index-5tKd4Cpp.js:15:24601)
```
