### ISSUE TITLE
Azure storage fail to upload big files with IllegalStateException

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5383]
### Describe the issue

When trying to execute a flow with a FILE input using a large file (4MB for ex),  it fails with an error `java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-1-3` with the Azure internal storage.

```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-1-3
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1779)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:146)
	at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:337)
	at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:298)
	at com.azure.storage.blob.BlobClient.upload(BlobClient.java:243)
	at io.kestra.storage.azure.AzureStorage.put(AzureStorage.java:199)
	at io.kestra.core.storages.StorageInterface.put(StorageInterface.java:75)
	at io.kestra.core.storages.StorageInterface.from(StorageInterface.java:96)
	at io.kestra.core.runners.FlowInputOutput.lambda$readData$2(FlowInputOutput.java:166)
```

Upstream issue TBD

### Environment

- Kestra Version: 0.20.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Upstream issue: https://github.com/Azure/azure-sdk-for-java/issues/42268
