### ISSUE TITLE
Editor documentation lists non-existant Pebble filters

### ISSUE THREAD

**Issue by Tschrock** [kestra-io/kestra#5436]
### Describe the issue

The documentation that shows up in the sidebar in the flow editor shows some filters that don't seem to exist - trying to use them fails like below:
```
2024-10-13 04:24:21.979

io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
2024-10-13 04:24:21.979

io.kestra.core.exceptions.IllegalVariableEvaluationException: io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
    at io.kestra.core.runners.VariableRenderer.properPebbleException(VariableRenderer.java:64)
    at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:120)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:91)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:76)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:68)
    at io.kestra.core.runners.DefaultRunContext.render(DefaultRunContext.java:186)
    at io.kestra.plugin.core.log.Log.run(Log.java:80) at io.kestra.plugin.core.log.Log.run(Log.java:21)
    at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
    at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
Caused by: io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
    at io.pebbletemplates.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:49)
    at io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
    at io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
    at io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
    at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
    at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:96)
    at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:114) ... 8 more
```

![](https://p.cp3.es/ss1728808081-22c655.png)

I tested md5, sha1, and truncate and they fail - there's probably a few more in there.

### Environment

- Kestra Version: 0.19.2 - 4338437 Tue, Oct 8, 2024 9:52 AM
- Operating System (OS/Docker/Kubernetes): Docker (kestra/kestra:latest)
- Java Version (if you don't run kestra in Docker):

**Comment by SayedQassim** [comment]
Hi @MilosPaunovic, I approached this issue and the same error occurred, I went over the repo and saw that @anna-geller added the documentation for it, from what I understanded that filters are coming from PebbleTemplates/pebble which they have an implementation for sha256, but not for the other algorithms, I saw also custom filters, so I added new implementation class for sha1, and sha256 and It worked absolutely fine. please assign me to the issue and I will create a PR if you are happy with the approach I solved the issue with.

**Comment by Skraye** [comment]
Hi @SayedQassim ! Feel free to open your PR! :rocket:
