### ISSUE TITLE
Quick Start Installation with Certificate Issue

### ISSUE THREAD

**Issue by timmapuramreddy** [kestra-io/kestra#5451]
### Feature description

I just started following the Docs and started Quick Start using the command : docker run --pull=always --rm -it -p 8181:8181 --user=root -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp kestra/kestra:latest server local, changed port to 8181 as already 8080 is bind with other app, However i am getting an error
latest: Pulling from kestra/kestra
4be1db8bbbeb: Pull complete
8cc429601029: Pull complete
5bb97d9b04cd: Pull complete
44efd14ea121: Pull complete
e7a975d7275d: Pull complete
7e3508809d5a: Pull complete
ba9189ac610d: Pull complete
7bef88828e83: Pull complete
198b4044968d: Pull complete
Digest: sha256:13341fc76357f4167135604b69b4755855c9f240248a2965c724d4da9a3c5762
Status: Downloaded newer image for kestra/kestra:latest
2024-10-14 08:27:53,424 INFO  main         org.flywaydb.core.FlywayExecutor Database: jdbc:h2:file:/app/data/database (H2 2.3)
2024-10-14 08:27:53,431 WARN  main         o.f.c.i.database.base.Database Flyway upgrade recommended: H2 2.3.232 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.224.
2024-10-14 08:27:53,461 INFO  main         o.f.c.i.s.JdbcTableSchemaHistory Schema history table "PUBLIC"."flyway_schema_history" does not exist yet
2024-10-14 08:27:53,464 INFO  main         o.f.core.internal.command.DbValidate Successfully validated 19 migrations (execution time 00:00.015s)
2024-10-14 08:27:53,472 INFO  main         o.f.c.i.s.JdbcTableSchemaHistory Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2024-10-14 08:27:53,503 INFO  main         o.f.core.internal.command.DbMigrate Current version of schema "PUBLIC": << Empty Schema >>
2024-10-14 08:27:53,527 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.1 - initial"
2024-10-14 08:27:53,673 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.2 - worker heartbeat"
2024-10-14 08:27:53,679 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.3 - worker heartbeat"
2024-10-14 08:27:53,686 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.4 - multitenant"
2024-10-14 08:27:53,725 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.5 - multitenant on multipleconditions"
2024-10-14 08:27:53,732 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.6 - execution queued"
2024-10-14 08:27:53,737 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.7 - execution cancelled"
2024-10-14 08:27:53,744 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.8 - execution queued"
2024-10-14 08:27:53,751 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.9 - multitenant indices"
2024-10-14 08:27:53,761 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.12 - execution triggerid"
2024-10-14 08:27:53,769 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.13 - log fulltext"
2024-10-14 08:27:53,775 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.14 - subflow executions"
2024-10-14 08:27:53,782 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.15 - trigger store next date"
2024-10-14 08:27:53,787 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.16 - log timestamp index"
2024-10-14 08:27:53,793 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.17 - service instance"
2024-10-14 08:27:53,798 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.18 - retry revamp"
2024-10-14 08:27:53,805 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.19 - retry flow"
2024-10-14 08:27:53,809 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.20 - drop worker instance"
2024-10-14 08:27:53,813 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.21 - trigger worker id"
2024-10-14 08:27:53,820 INFO  main         o.f.core.internal.command.DbMigrate Successfully applied 19 migrations to schema "PUBLIC", now at version v1.21 (execution time 00:00.222s)
2024-10-14 08:27:54,999 INFO  local        io.kestra.cli.AbstractCommand Starting Kestra 0.19.2 with environments [cli] [revision 4338437 / 2024-10-08T13:52]
2024-10-14 08:27:55,096 INFO  local        i.kestra.core.plugins.PluginScanner Registered 79 core plugins (scan done in 89ms)
2024-10-14 08:27:55,678 INFO  local        i.kestra.core.plugins.PluginScanner Registered 486 plugins from 97 groups (scan done in 578ms)
2024-10-14 08:27:56,210 INFO  local        io.kestra.cli.AbstractCommand Server Running: http://1e81e7545597:8080/, Management server on port http://1e81e7545597:47615/health
2024-10-14 08:27:56,979 WARN  local        i.k.w.services.FlowAutoLoaderService Unable to load "Getting Started" flows from community blueprints. You can disable this feature by setting 'kestra.tutorial-flows.enabled=false'. Cause: Client 'api': Connect Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-10-14 08:27:57,040 ERROR default-nioEventLoopGroup-1-4 i.m.h.client.netty.DefaultHttpClient Failed to connect to remote
[javax.net](http://javax.net/).ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1671)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1517)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1358)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1407)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 32 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 37 common frames omitted

**Comment by Ben8t** [comment]
Kestra server run by default on port 8080. You should either bind the corresponding ports in Docker or change Kestra configuration (you can use the docker-compose installation that comes with configuration variables).
https://kestra.io/docs/installation/docker-compose

**Comment by timmapuramreddy** [comment]
Event after trying with 8080 i am getting the error, Can you please have a look at the below error

docker run --pull=always --rm -it -p 8080:8080 --user=root -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp kestra/kestra:latest server local                                                ─╯
latest: Pulling from kestra/kestra
4be1db8bbbeb: Pull complete
8cc429601029: Pull complete
5bb97d9b04cd: Pull complete
44efd14ea121: Pull complete
e7a975d7275d: Pull complete
f6ee81805a9f: Pull complete
8466e4e97e2b: Pull complete
9c04cd72aceb: Pull complete
9e4c3fdfcdc1: Pull complete
Digest: sha256:1e8e4e52e59c6def2c9d71ee6d7c1f7c80e25faaeb9dcb635d25f8c04a446bc4
Status: Downloaded newer image for kestra/kestra:latest
2024-10-21 12:51:52,297 INFO  main         org.flywaydb.core.FlywayExecutor Database: jdbc:h2:file:/app/data/database (H2 2.3)
2024-10-21 12:51:52,303 WARN  main         o.f.c.i.database.base.Database Flyway upgrade recommended: H2 2.3.232 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.224.
2024-10-21 12:51:52,329 INFO  main         o.f.c.i.s.JdbcTableSchemaHistory Schema history table "PUBLIC"."flyway_schema_history" does not exist yet
2024-10-21 12:51:52,331 INFO  main         o.f.core.internal.command.DbValidate Successfully validated 19 migrations (execution time 00:00.014s)
2024-10-21 12:51:52,337 INFO  main         o.f.c.i.s.JdbcTableSchemaHistory Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2024-10-21 12:51:52,362 INFO  main         o.f.core.internal.command.DbMigrate Current version of schema "PUBLIC": << Empty Schema >>
2024-10-21 12:51:52,381 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.1 - initial"
2024-10-21 12:51:52,602 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.2 - worker heartbeat"
2024-10-21 12:51:52,608 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.3 - worker heartbeat"
2024-10-21 12:51:52,612 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.4 - multitenant"
2024-10-21 12:51:52,652 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.5 - multitenant on multipleconditions"
2024-10-21 12:51:52,659 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.6 - execution queued"
2024-10-21 12:51:52,663 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.7 - execution cancelled"
2024-10-21 12:51:52,670 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.8 - execution queued"
2024-10-21 12:51:52,679 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.9 - multitenant indices"
2024-10-21 12:51:52,687 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.12 - execution triggerid"
2024-10-21 12:51:52,695 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.13 - log fulltext"
2024-10-21 12:51:52,703 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.14 - subflow executions"
2024-10-21 12:51:52,708 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.15 - trigger store next date"
2024-10-21 12:51:52,723 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.16 - log timestamp index"
2024-10-21 12:51:52,728 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.17 - service instance"
2024-10-21 12:51:52,732 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.18 - retry revamp"
2024-10-21 12:51:52,738 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.19 - retry flow"
2024-10-21 12:51:52,743 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.20 - drop worker instance"
2024-10-21 12:51:52,748 INFO  main         o.f.core.internal.command.DbMigrate Migrating schema "PUBLIC" to version "1.21 - trigger worker id"
2024-10-21 12:51:52,754 INFO  main         o.f.core.internal.command.DbMigrate Successfully applied 19 migrations to schema "PUBLIC", now at version v1.21 (execution time 00:00.294s)
2024-10-21 12:51:53,713 INFO  local        io.kestra.cli.AbstractCommand Starting Kestra 0.19.4 with environments [cli] [revision c7288bd / 2024-10-18T09:08]
2024-10-21 12:51:53,800 INFO  local        i.kestra.core.plugins.PluginScanner Registered 79 core plugins (scan done in 80ms)
2024-10-21 12:51:54,338 INFO  local        i.kestra.core.plugins.PluginScanner Registered 486 plugins from 97 groups (scan done in 535ms)
2024-10-21 12:51:54,870 INFO  local        io.kestra.cli.AbstractCommand Server Running: http://d657462c32d4:8080, Management server on port http://d657462c32d4:30100/health
2024-10-21 12:51:56,054 WARN  local        i.k.w.services.FlowAutoLoaderService Unable to load "Getting Started" flows from community blueprints. You can disable this feature by setting 'kestra.tutorial-flows.enabled=false'. Cause: Client 'api': Connect Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
**2024-10-21 12:51:56,109 ERROR default-nioEventLoopGroup-1-4 i.m.h.client.netty.DefaultHttpClient Failed to connect to remote
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1671)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1517)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1358)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1407)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 32 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 37 common frames omitted**

**Comment by Ben8t** [comment]
Can you provide more details about the service currently running on your machine and port used ?
Also what's your OS specification ?

**Comment by tchiotludo** [comment]
And most important, are you able to see kestra ui? 

It seems that you have a custom environments (possibly air-gapped with no internet connection, or ssl offload), you are unable to reach our api to fetch examples flow that we load at startup. You can disabled it using env variable: `-e "KESTRA_TUTORIAL_FLOWS_ENABLED: false"`. 

But at the end, it should not prevent to start Kestra and use it.

**Comment by anna-geller** [comment]
closing as no feedback received on the issue for 5 months
