### ISSUE TITLE
HTTP Trigger using method: HEAD fails

### ISSUE THREAD

**Issue by Tschrock** [kestra-io/kestra#5459]
### Describe the issue

Creating an HTTP trigger with `method: HEAD` will fail to execute. The logs show it successfully making the http request but then failing with a NullPointerException.

```
[namespace: cp3] [flow: http-trigger-test] [trigger: http_check] [date: 2024-10-14T21:10:15.841Z] Trigger evaluation failed in the worker with error: null
```
```
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Unknown Source)
at java.base/java.util.ImmutableCollections$MapN.<init>(Unknown Source)
at java.base/java.util.Map.of(Unknown Source)
at io.kestra.plugin.core.http.Trigger.evaluate(Trigger.java:157)
at io.kestra.core.runners.WorkerTriggerThread.doRun(WorkerTriggerThread.java:24)
at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

```yaml
id: http-trigger-test
namespace: cp3
triggers:
  - id: http_check
    type: io.kestra.plugin.core.http.Trigger
    uri: https://example.com
    method: HEAD
    interval: PT30S
tasks:
  - id: log-stats
    type: io.kestra.plugin.core.log.Log
    message: "Triggered flow!"
```

![](https://p.cp3.es/ss1728940248-2d5494.png)

### Environment

- Kestra Version: 0.19.2 - 4338437 Tue, Oct 8, 2024 9:52 AM
- Operating System (OS/Docker/Kubernetes): Docker (kestra/kestra:latest)
- Java Version (if you don't run kestra in Docker):

**Comment by Harsh4902** [comment]
@anna-geller Can I work on this issue?

**Comment by anna-geller** [comment]
for sure, go for it! thanks a lot
