### ISSUE TITLE
Better error message (possibly with guide on website) when docker socket is not found / we don't have right

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#5524]
### Describe the issue

When docker socket is not accessible / not found it throws 
```
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory
 at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:210)
 at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
 at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
 at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
 at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory
 at com.github.dockerjava.transport.DomainSocket.<init>(DomainSocket.java:63)
 at com.github.dockerjava.transport.LinuxDomainSocket.<init>(LinuxDomainSocket.java:41)
 at com.github.dockerjava.transport.DomainSocket.get(DomainSocket.java:140)
 at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
```
stacktrace which is not descriptive at all.

We should either try-catch or check if socket doesn't exist and throw a proper error describing the user why it's not working (socket is not mounted / no right on it) and possibly a way to resolve it

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Ideally we should validate the Docker environment before using it.
There may be a way to do it via the client, I know testcontainers do it for ex.

**Comment by brian-mulier-p** [comment]
I looked at test containers implem and they do a strong docker socket right check + scheme-dependant tests https://github.com/testcontainers/testcontainers-java/blob/29b0c5fbea772a60ece684433e9e219ec0384740/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L158-L222

I find it simpler to catch the error tbh and not bother with all the test as there may be some edge case setup...
