### ISSUE TITLE
RunContext.render don't handle List<Map>

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#598]
### Discussed in https://github.com/kestra-io/kestra/discussions/597

<div type='discussions-op-text'>

<sup>Originally posted by **lanore78** May  6, 2022</sup>
Hello, 

I'm trying to use elasticsearch. Scroll plugin, and got error while parsing request.

Here is error logs
```
2022-05-06 16:52:52.685 class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
2022-05-06 16:52:52.685java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:182)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:165)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:163)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:163)
	at io.kestra.core.runners.RunContext.render(RunContext.java:391)
	at io.kestra.plugin.elasticsearch.ElasticsearchService.toBody(ElasticsearchService.java:20)
	at io.kestra.plugin.elasticsearch.ElasticsearchService.toXContentParser(ElasticsearchService.java:27)
	at io.kestra.plugin.elasticsearch.AbstractSearch.request(AbstractSearch.java:48)
	at io.kestra.plugin.elasticsearch.Scroll.run(Scroll.java:71)
	at io.kestra.plugin.elasticsearch.Scroll.run(Scroll.java:33)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:499)
```

And, This is flow definition
```
tasks:
  - id: query
    type: io.kestra.plugin.elasticsearch.Scroll
    connection:
      headers:
        - "Authorization: Basic basic auth key=="
      hosts:
        - https://my-elasticsearch-domain:9200
    indexes:
      - filebeat-*
    request:
      query:
        bool:
          filter:
            - range:
                "@timestamp":
                  format: epoch_millis
                  gte: 1651648888506
                  lte: 1651652488506
            - query_string:
                analyze_wildcard: true
                query: "log.level : ERROR"
      size: 1000
    routing: dummy
```

I tried same query directly using XContentParser API of OpenSearch as follow and it has no problem.

```
        String yaml = "size: 1000\n" +
                "query:\n" +
                "  bool:\n" +
                "    filter:\n" +
                "    - range:\n" +
                "        \"@timestamp\":\n" +
                "          gte: 1651648888506\n" +
                "          lte: 1651652488506\n" +
                "          format: epoch_millis\n" +
                "    - query_string:\n" +
                "        analyze_wildcard: true\n" +
                "        query: \"log.level : ERROR\"\n";

        SearchModule searchModule = new SearchModule(Settings.EMPTY, false, Collections.emptyList());

        XContentParser xContentParser = XContentFactory.xContent(XContentType.YAML).createParser(
                new NamedXContentRegistry(searchModule.getNamedXContents()),
                LoggingDeprecationHandler.THROW_UNSUPPORTED_OPERATION,
                yaml
        );

        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
        searchSourceBuilder.parseXContent(xContentParser);

        System.out.println(searchSourceBuilder);
```

When I run this code, I got this output.

```
{"size":1000,"query":{"bool":{"filter":[{"range":{"@timestamp":{"from":1651648888506,"to":1651652488506,"include_lower":true,"include_upper":true,"format":"epoch_millis","boost":1.0}}},{"query_string":{"query":"log.level : ERROR","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"analyze_wildcard":true,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}
```

I guess there are some conflict between OpenSearch XContents spec and Kestra VariableRenderer.

Since, Flow definition is yaml format, how about using XContentsType.YAML instead of [JSON](https://github.com/kestra-io/plugin-elasticsearch/blob/8333d4e29dd77e567ef4ff67602f1f2cb5f67107/src/main/java/io/kestra/plugin/elasticsearch/AbstractSearch.java#L42) 
In that way, no need to convert request param from yaml to json.

</div>

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra/commit/c9d5f249b08b1f285e9dd73d985cf1ccb6ae2f26
