### ISSUE TITLE
Error with Execution on Subflow that has FILE or JSON outputs

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6308]
### Describe the issue

- Execute Workflow
- Workflow calls a Subfow that generates FILE and JSON outputs
    - does appear to work with STRING type, but we are unable to adjust our flows for this due to reliance on FILE output type from subflow
- execution fails with no logs
    - @tchiotludo  identified some cloud logs in backend that it might be related to JSON/FILE output type

- image of no logs
<img width="1157" alt="Screenshot 2024-12-05 at 12 04 59 AM" src="https://github.com/user-attachments/assets/426c8eec-dcc6-4ba7-adf1-acef16aa9109">

- note - it appears that the subflow does finish, but debug outputs is broken in the **parent** flow, it does show output in subflow
    - second bottom outputs, will not debug, eventually shows error that "task" is missing from outputs (this is from Parent flow)
<img width="681" alt="Screenshot 2024-12-05 at 12 05 37 AM" src="https://github.com/user-attachments/assets/d87894f1-f473-44d6-b2fd-77400cf9a39d">

### Environment

- Kestra Version: `0.20.1`

**Comment by Ben8t** [comment]
Here is a reproducer:

```yaml
id: main_flow
namespace: company

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: child_flow
    namespace: company
    wait: true
```

```
id: child_flow
namespace: company

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: http
    type: io.kestra.plugin.core.http.Request
    uri: 'https://dummyjson.com/products'

outputs:
  - id: data_file
    type: FILE
    value: "{{ outputs.download.uri }}"

  - id: data_json
    type: JSON
    value: "{{ json(outputs.http.body) }}"
```

I'm getting same behavior: parent flow errors at subflow execution, but the subflow execution itself is SUCCESS (with outputs)

**Comment by qui458** [comment]
I can second to this issue,  but was able to fetch some logs from container:

```
2024-12-05 08:13:10,289 ERROR jdbc-queue-Execution_0 io.kestra.jdbc.runner.JdbcExecutor Unable to create the Subflow Execution Result
jakarta.validation.ConstraintViolationException: order_edi_file: Invalid output for `order_edi_file`, Illegal character in path at index 0: {{ outputs.run.outputFiles['SUP5790000432141_ORD1109684_STO1186.dat'] }}, but received `{{ outputs.run.outputFiles['SUP5790000432141_ORD1109684_STO1186.dat'] }}`
        at io.kestra.core.models.validations.ManualConstraintViolation.toConstraintViolationException(ManualConstraintViolation.java:62)
        at io.kestra.core.models.flows.Data.toConstraintViolationException(Data.java:36)
        at io.kestra.core.runners.FlowInputOutput.lambda$typedOutputs$19(FlowInputOutput.java:398)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.kestra.core.runners.FlowInputOutput.typedOutputs(FlowInputOutput.java:403)
        at io.kestra.plugin.core.flow.Subflow.lambda$createSubflowExecutionResult$1(Subflow.java:209)
        at java.base/java.util.Optional.map(Unknown Source)
        at io.kestra.plugin.core.flow.Subflow.createSubflowExecutionResult(Subflow.java:209)
        at io.kestra.jdbc.runner.JdbcExecutor.sendSubflowExecutionResult(JdbcExecutor.java:587)
        at io.kestra.jdbc.runner.JdbcExecutor.lambda$toExecution$24(JdbcExecutor.java:915)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at io.kestra.jdbc.runner.JdbcExecutor.toExecution(JdbcExecutor.java:912)
        at io.kestra.jdbc.runner.JdbcExecutor.toExecution(JdbcExecutor.java:864)
        at io.kestra.jdbc.runner.JdbcExecutor.executionQueue(JdbcExecutor.java:570)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at io.kestra.jdbc.runner.JdbcQueue.lambda$receive$7(JdbcQueue.java:264)
        at io.kestra.jdbc.runner.JdbcQueue.lambda$receiveImpl$11(JdbcQueue.java:333)
        at io.kestra.jdbc.runner.JdbcQueue.lambda$poll$12(JdbcQueue.java:356)
        at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

my subflow:
```
id: order_convert
namespace: demo

inputs:
  - id: order_ion_file
    type: FILE
    required: true

outputs:
  - id: order_edi_file
    type: FILE
    value: "{{ outputs.run.outputFiles['SUP5790000432141_ORD1109684_STO1186.dat'] }}"

tasks:
  - id: run
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
      include:
        - scripts/supplier/*.py
    inputFiles:
      order.ion: "{{ inputs.order_ion_file }}"
    outputFiles:
      - "*.dat"
    commands:
      - python scripts/supplier/supplier_order_to_edi.py
```

the available subflow execution result:
![image](https://github.com/user-attachments/assets/2ec90b8a-38d1-41c6-a66a-0ec2fc67e0c1)

main flow execution:
![image](https://github.com/user-attachments/assets/01899d3b-6763-4ce6-bc9a-fa1e1b89bc41)

with 0.19.x version it is no problem at all, it started happening with 0.20.x now.
