### ISSUE TITLE
mapping type 'flattened' is missing while using AWS opensearch

### ISSUE THREAD

**Issue by mengzhuo** [kestra-io/kestra#678]
### Expected Behavior

Every things works fine.

### Actual Behaviour

```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.kestra.core.services.ExecutionService]

Message: OpenSearch exception [type=action_request_validation_exception, reason=Validation Failed: 1: mapping type is missing;]
Path Taken: new KafkaExecutor() --> KafkaExecutor.kafkaExecutors --> ExecutorMain.executionService --> ExecutionService.flowRepositoryInterface
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2035)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1579)
        at io.kestra.core.services.$ExecutionService$Definition.injectBean(Unknown Source)
        at io.kestra.core.services.$ExecutionService$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2035)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1579)
        at io.kestra.runner.kafka.executors.$ExecutorMain$Definition.injectBean(Unknown Source)
        at io.kestra.runner.kafka.executors.$ExecutorMain$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3685)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3591)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1376)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBeansOfType(AbstractInitializableBeanDefinition.java:2132)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeansOfTypeForField(AbstractInitializableBeanDefinition.java:1744)
        at io.kestra.runner.kafka.$KafkaExecutor$Definition.injectBean(Unknown Source)
        at io.kestra.runner.kafka.$KafkaExecutor$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:888)
        at io.kestra.cli.commands.servers.ExecutorCommand.call(ExecutorCommand.java:34)
        at io.kestra.cli.commands.servers.ExecutorCommand.call(ExecutorCommand.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.kestra.cli.App.execute(App.java:67)
        at io.kestra.cli.App.main(App.java:47)
Caused by: OpenSearchStatusException[OpenSearch exception [type=action_request_validation_exception, reason=Validation Failed: 1: mapping type is missing;]]
        at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207)
        at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2079)
        at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2056)
        at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1775)
        at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1745)
        at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1709)
        at org.opensearch.client.IndicesClient.putMapping(IndicesClient.java:373)
        at io.kestra.repository.elasticsearch.ElasticSearchIndicesService.updateMapping(ElasticSearchIndicesService.java:71)
        at io.kestra.repository.elasticsearch.AbstractElasticSearchRepository.initMapping(AbstractElasticSearchRepository.java:456)
        at io.kestra.repository.elasticsearch.$ElasticSearchFlowRepository$Definition.initialize(Unknown Source)
        at io.kestra.repository.elasticsearch.$ElasticSearchFlowRepository$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        ... 44 more
        Suppressed: org.opensearch.client.ResponseException: method [PUT], host [https://vpc-example-kestra-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.us-west-2.es.amazonaws.com], URI [/kestra_flows/_mapping?master_timeout=30s&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false&ignore_throttled=false&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"},"status":400}
                at org.opensearch.client.RestClient.convertResponse(RestClient.java:350)
                at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
                at org.opensearch.client.RestClient.performRequest(RestClient.java:295)
                at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762)
                ... 52 more

```

### Steps To Reproduce

1. setup opensearch v1.3 / elasticsearch 7.0 / elasticsearch 6.8 
2. kestra config using those endpoint
3. start pods

### Environment Information

- Kestra Version: 0.5.0-beta
- Operating System (OS / Docker / Kubernetes): k8s

**Comment by tchiotludo** [comment]
Hey @mengzhuo, 
it's fixed with latest dev version, simply use image tag `develop` or wait few days I think for the next release, as you want
