### ISSUE TITLE
Kestra standalone JAR in local mode didn't seems to work anymore

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#880]
### Actual Behaviour

Kestra standalone JAR in local mode didn't work anymore, the UI never ends loading.

### Steps To Reproduce

1. Download Kestra standalone JAR
2. Unzip it
3. Launch `./kestra-0.5.2 server local`
4. Open http://localhost:8080

### Environment Information

- Kestra Version: 0.5.2
- Operating System (OS / Docker / Kubernetes): Linux
- Java Version (If not docker): 11

**Comment by loicmathieu** [comment]
This is a frontend error

```
chunk-vendors.51461e22.js:323 TypeError: Cannot read properties of undefined (reading 'forEach')
    at a.switchTheme (index.a88b8582.js:1:20003)
    at a.displayApp (index.a88b8582.js:1:18598)
    at a.created (index.a88b8582.js:1:18301)
    at ie (chunk-vendors.51461e22.js:323:11710)
    at Rn (chunk-vendors.51461e22.js:323:29272)
    at t._init (chunk-vendors.51461e22.js:323:34625)
    at new a (chunk-vendors.51461e22.js:323:35885)
    at un (chunk-vendors.51461e22.js:323:21822)
    at init (chunk-vendors.51461e22.js:323:20688)
    at p (chunk-vendors.51461e22.js:323:44601)
```

**Comment by loicmathieu** [comment]
The same issue occurs when using the Kestra JAR with the standalone command

**Comment by tchiotludo** [comment]
The issue is related to usage with new version that break the old one, there is a local storage conflict, just deleted the local storage on `theme` key

**Comment by loicmathieu** [comment]
Tested it and it works, thanks for the tip.
