### ISSUE TITLE
Kestra standalone JAR in standalone mode didn't seems to work anymore

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#881]
### Actual Behaviour

When using the standalone JAR with a local configuration file inside `$PWD/confs/application.yml` it crash with the following error

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [executionQueue] of class: io.kestra.core.runners.StandAloneRunner

Message: No bean of type [io.kestra.core.queues.QueueInterface<io.kestra.core.models.executions.Execution>] exists for the given qualifier: @Named('executionQueue'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new StandAloneRunner() --> StandAloneRunner.executionQueue
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
	at io.kestra.core.runners.$StandAloneRunner$Definition.injectBean(Unknown Source)
	at io.kestra.core.runners.$StandAloneRunner$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2906)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
	at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:56)
	at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:18)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.kestra.cli.App.execute(App.java:67)
	at io.kestra.cli.App.main(App.java:47)
```

### Steps To Reproduce

1. Download Kestra standalone JAR
2. Starts a Postgres database: `docker run --rm -e POSTGRES_USER=kestra            -e POSTGRES_PASSWORD=k3str4 -e POSTGRES_DB=kestra            -p 5432:5432 postgres:14.1`
3. Create a `$PWD/confs/application.yml` configuration file with the following content
```yaml
datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
```
4. Launch the standalone JAR: `./kestra-0.5.2 server standalone`

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
This is not correct and works as expected with config file denoted via `-c` or in the `~/.kestra/config.yml` file.
